package iptables

// This file is part of the PURE half of the package: it turns a live rule set
// that someone else read off the host into a verdict per rule, and parses the
// iptables-save text that reader produces. Running iptables-save is in
// reconcile.go, with the rest of the privileged surface.

import (
	"bufio"
	"strings"
)

// State is the classification outcome for a live iptables rule.
type State string

const (
	// StateExpected — rule matches something horizon would generate right
	// now under current config.
	StateExpected State = "expected"

	// StateStale — rule matches something horizon *would have generated*
	// under the previous iface/CIDR (cfg.LastLocalIface / LastLanCIDR).
	// Auto-heal deletes these.
	StateStale State = "stale"

	// StateBlessed — admin added this canonical form to
	// cfg.BlessedIPTablesRules. Auto-heal never touches it.
	StateBlessed State = "blessed"

	// StateUnknown — rule is none of the above. Auto-heal never touches
	// it; surface in the UI so the admin can bless or remove.
	StateUnknown State = "unknown"
)

// ClassifiedRule is a live rule plus its classification and reason.
type ClassifiedRule struct {
	Rule   Rule   `json:"rule"`
	State  State  `json:"state"`
	Reason string `json:"reason,omitempty"`
}

// Summary returns the counts of each state. Useful for the fleet payload
// that surfaces peer health.
type Summary struct {
	Expected int `json:"expected"`
	Stale    int `json:"stale"`
	Blessed  int `json:"blessed"`
	Unknown  int `json:"unknown"`
}

// Classify compares each live rule against the expected, stale, and blessed
// sets, returning one ClassifiedRule per input. Input order is preserved.
//
// Classification precedence (first match wins):
//  1. expected (currently wanted) — takes priority over everything else
//  2. blessed  (admin-approved external) — so a rule horizon wants AND the
//     admin blessed still shows as expected (more useful for UX)
//  3. stale    (was-ours under prior iface/CIDR)
//  4. unknown
//
// The expected > blessed ordering matters when an admin blesses something
// that later becomes expected (e.g. they blessed a MASQUERADE for eth1
// before the default route flipped, then it flipped, and now horizon wants
// exactly that rule).
func Classify(live, expected, stale []Rule, blessed []string) []ClassifiedRule {
	expSet := make(map[string]struct{}, len(expected))
	for _, r := range expected {
		expSet[r.Canonical()] = struct{}{}
	}
	staleSet := make(map[string]struct{}, len(stale))
	for _, r := range stale {
		staleSet[r.Canonical()] = struct{}{}
	}
	blessedSet := make(map[string]struct{}, len(blessed))
	for _, c := range blessed {
		blessedSet[c] = struct{}{}
	}

	out := make([]ClassifiedRule, 0, len(live))
	for _, r := range live {
		canon := r.Canonical()
		var state State
		var reason string
		switch {
		case hasKey(expSet, canon):
			state = StateExpected
		case hasKey(blessedSet, canon):
			state = StateBlessed
			reason = "admin-blessed"
		case hasKey(staleSet, canon):
			state = StateStale
			reason = "matches a rule horizon would have emitted under the previous iface/CIDR — auto-heal will remove"
		default:
			state = StateUnknown
			reason = "not generated by horizon and not admin-blessed"
		}
		out = append(out, ClassifiedRule{Rule: r, State: state, Reason: reason})
	}
	return out
}

// SummarizeClassified aggregates counts by state.
func SummarizeClassified(classified []ClassifiedRule) Summary {
	var s Summary
	for _, c := range classified {
		switch c.State {
		case StateExpected:
			s.Expected++
		case StateStale:
			s.Stale++
		case StateBlessed:
			s.Blessed++
		case StateUnknown:
			s.Unknown++
		}
	}
	return s
}

func hasKey(m map[string]struct{}, k string) bool {
	_, ok := m[k]
	return ok
}

// scopeLiveRules drops the rules in shared built-in chains that horizon has no
// claim on. INPUT keeps the jump to WG-INPUT and source-DROP rules; nat
// PREROUTING keeps only the jump to HZ-PREROUTING. Both chains are routinely
// full of other tools' rules — Docker puts `-m addrtype --dst-type LOCAL -j
// DOCKER` in PREROUTING — and classifying those as "unknown" would bury the
// IPTables tab in rules the admin cannot act on.
//
// WHY INPUT ADMITS SOURCE-DROPS. `-s <addr> -j DROP` is the shape of an IP
// ban, and a ban is a rule horizon writes (handlers_ban.go today, the agent
// after item 12). It was outside the read scope, which is why a ban and
// horizon's own rules could not collide — but it is also why they could not be
// reconciled: the reconciler cannot heal, or decline to touch, a rule it never
// reads. So the shape comes in, with BannedIPs feeding the expected set from
// cfg.IPBans, and a ban classifies as horizon's own.
//
// WIDENING THE READ DOES NOT WIDEN THE DELETE, and that is the property this
// change lives or dies on. Reconcile removes exactly one classification —
// stale, meaning "horizon would have emitted this under the previous
// iface/CIDR" — and nothing derives stale from a source-DROP in INPUT
// (StaleRules says why it leaves bans out). Everything else newly visible here
// lands in unknown or blessed, both of which are surfaced and left alone. The
// hand-added DROP that proves it is TestReconcileLeavesAHandAddedInputDropAlone,
// which asserts on the iptables commands issued, not on the verdict.
func scopeLiveRules(rules []Rule) []Rule {
	out := make([]Rule, 0, len(rules))
	for _, r := range rules {
		if r.Table == "filter" && r.Chain == "INPUT" &&
			!jumpsTo(r.Args, InputChainName) && !isSourceDropShape(r.Args) {
			continue
		}
		if r.Table == "nat" && r.Chain == "PREROUTING" && !jumpsTo(r.Args, PreroutingChainName) {
			continue
		}
		out = append(out, r)
	}
	return out
}

// isSourceDropShape reports whether a rule body is the exact 4-token shape of
// an IP ban: ["-s", "<addr>", "-j", "DROP"]. That is what handlers_ban.go
// inserts (and what iptables-save prints back, with the /32 filled in), and it
// is the only INPUT shape besides horizon's own jump that scopeLiveRules lets
// through.
//
// EXACT ON PURPOSE. The token count and positions are checked rather than
// scanned for, the same discipline isHorizonMasqShape follows: an admin's
// `-s 192.0.2.0/24 -p tcp -j DROP`, a negated `! -s … -j DROP`, or a rule that
// happens to mention a source somewhere are all different rules, and each one
// admitted is a line in the IPTables tab the admin has to read past. The
// narrowing this widens exists so that tab stays actionable.
//
// It does NOT check that the source is horizon's — a hand-typed DROP for an
// address that was never banned matches this shape and is admitted. That is
// the point: horizon can only leave a rule alone deliberately if it can see it.
// The classifier then calls it unknown, and unknown is never deleted.
func isSourceDropShape(args []string) bool {
	return len(args) == 4 &&
		args[0] == "-s" &&
		args[2] == "-j" &&
		args[3] == "DROP"
}

// jumpsTo reports whether a rule body ends in a jump to the named target.
func jumpsTo(args []string, target string) bool {
	for i := 0; i+1 < len(args); i++ {
		if args[i] == "-j" && args[i+1] == target {
			return true
		}
	}
	return false
}

// parseIptablesSave extracts `-A <chain> <args>` lines from iptables-save
// output, limited to the chains we care about. Exposed for testing.
func parseIptablesSave(output, table string, chains []string) []Rule {
	wanted := make(map[string]bool, len(chains))
	for _, c := range chains {
		wanted[c] = true
	}

	var rules []Rule
	sc := bufio.NewScanner(strings.NewReader(output))
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if !strings.HasPrefix(line, "-A ") {
			continue
		}
		// "-A CHAIN arg1 arg2 ..." → split on first two spaces.
		fields := strings.SplitN(line, " ", 3)
		if len(fields) < 3 {
			continue
		}
		chain := fields[1]
		if !wanted[chain] {
			continue
		}
		rules = append(rules, Rule{
			Table: table,
			Chain: chain,
			Args:  strings.Fields(fields[2]),
		})
	}
	return rules
}
