package iptables

import (
	"bufio"
	"fmt"
	"os/exec"
	"strings"
)

// State is the classification outcome for a live iptables rule.
type State string

const (
	// StateExpected — rule matches something horizon would generate right
	// now under current config.
	StateExpected State = "expected"

	// StateStale — rule matches something horizon *would have generated*
	// under the previous iface/CIDR (cfg.LastLocalIface / LastLanCIDR).
	// Auto-heal deletes these.
	StateStale State = "stale"

	// StateBlessed — admin added this canonical form to
	// cfg.BlessedIPTablesRules. Auto-heal never touches it.
	StateBlessed State = "blessed"

	// StateUnknown — rule is none of the above. Auto-heal never touches
	// it; surface in the UI so the admin can bless or remove.
	StateUnknown State = "unknown"
)

// ClassifiedRule is a live rule plus its classification and reason.
type ClassifiedRule struct {
	Rule   Rule   `json:"rule"`
	State  State  `json:"state"`
	Reason string `json:"reason,omitempty"`
}

// Summary returns the counts of each state. Useful for the fleet payload
// that surfaces peer health.
type Summary struct {
	Expected int `json:"expected"`
	Stale    int `json:"stale"`
	Blessed  int `json:"blessed"`
	Unknown  int `json:"unknown"`
}

// Classify compares each live rule against the expected, stale, and blessed
// sets, returning one ClassifiedRule per input. Input order is preserved.
//
// Classification precedence (first match wins):
//  1. expected (currently wanted) — takes priority over everything else
//  2. blessed  (admin-approved external) — so a rule horizon wants AND the
//     admin blessed still shows as expected (more useful for UX)
//  3. stale    (was-ours under prior iface/CIDR)
//  4. unknown
//
// The expected > blessed ordering matters when an admin blesses something
// that later becomes expected (e.g. they blessed a MASQUERADE for eth1
// before the default route flipped, then it flipped, and now horizon wants
// exactly that rule).
func Classify(live, expected, stale []Rule, blessed []string) []ClassifiedRule {
	expSet := make(map[string]struct{}, len(expected))
	for _, r := range expected {
		expSet[r.Canonical()] = struct{}{}
	}
	staleSet := make(map[string]struct{}, len(stale))
	for _, r := range stale {
		staleSet[r.Canonical()] = struct{}{}
	}
	blessedSet := make(map[string]struct{}, len(blessed))
	for _, c := range blessed {
		blessedSet[c] = struct{}{}
	}

	out := make([]ClassifiedRule, 0, len(live))
	for _, r := range live {
		canon := r.Canonical()
		var state State
		var reason string
		switch {
		case hasKey(expSet, canon):
			state = StateExpected
		case hasKey(blessedSet, canon):
			state = StateBlessed
			reason = "admin-blessed"
		case hasKey(staleSet, canon):
			state = StateStale
			reason = "matches a rule horizon would have emitted under the previous iface/CIDR — auto-heal will remove"
		default:
			state = StateUnknown
			reason = "not generated by horizon and not admin-blessed"
		}
		out = append(out, ClassifiedRule{Rule: r, State: state, Reason: reason})
	}
	return out
}

// SummarizeClassified aggregates counts by state.
func SummarizeClassified(classified []ClassifiedRule) Summary {
	var s Summary
	for _, c := range classified {
		switch c.State {
		case StateExpected:
			s.Expected++
		case StateStale:
			s.Stale++
		case StateBlessed:
			s.Blessed++
		case StateUnknown:
			s.Unknown++
		}
	}
	return s
}

func hasKey(m map[string]struct{}, k string) bool {
	_, ok := m[k]
	return ok
}

// LiveRules reads horizon-managed rules from the host kernel via iptables-save.
// Scopes the read to the three chains horizon cares about; rules in other
// chains (OUTPUT, PREROUTING, custom admin chains, etc.) are not returned —
// that's part of the "horizon only manages what it manages" boundary.
//
// Returns an empty slice (not error) when iptables-save isn't available, so
// the classifier can still run on hosts without iptables installed yet.
func LiveRules() ([]Rule, error) {
	var all []Rule

	natRules, err := runIptablesSave("nat", []string{"POSTROUTING"})
	if err != nil {
		return nil, fmt.Errorf("iptables-save nat: %w", err)
	}
	all = append(all, natRules...)

	filterRules, err := runIptablesSave("filter", []string{"FORWARD", ForwardChainName})
	if err != nil {
		return nil, fmt.Errorf("iptables-save filter: %w", err)
	}
	all = append(all, filterRules...)

	return all, nil
}

// runIptablesSave executes `iptables-save -t <table>` and parses the output,
// filtering to rules in the given chains.
func runIptablesSave(table string, chains []string) ([]Rule, error) {
	cmd := exec.Command("iptables-save", "-t", table)
	out, err := cmd.Output()
	if err != nil {
		// iptables-save not installed, table missing, etc. Return empty so
		// the classifier treats "no live rules" as the input.
		return nil, nil
	}
	return parseIptablesSave(string(out), table, chains), nil
}

// parseIptablesSave extracts `-A <chain> <args>` lines from iptables-save
// output, limited to the chains we care about. Exposed for testing.
func parseIptablesSave(output, table string, chains []string) []Rule {
	wanted := make(map[string]bool, len(chains))
	for _, c := range chains {
		wanted[c] = true
	}

	var rules []Rule
	sc := bufio.NewScanner(strings.NewReader(output))
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if !strings.HasPrefix(line, "-A ") {
			continue
		}
		// "-A CHAIN arg1 arg2 ..." → split on first two spaces.
		fields := strings.SplitN(line, " ", 3)
		if len(fields) < 3 {
			continue
		}
		chain := fields[1]
		if !wanted[chain] {
			continue
		}
		rules = append(rules, Rule{
			Table: table,
			Chain: chain,
			Args:  strings.Fields(fields[2]),
		})
	}
	return rules
}
