// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

/**
 * Error response
 */
export interface ErrorResponse {
  error: string;
}
/**
 * OK response (used by many mutation endpoints)
 */
export interface OKResponse {
  ok: boolean;
}
export interface DashboardResponse {
  serviceCount: number /* int */;
  domainCount: number /* int */;
  zoneCount: number /* int */;
  peerCount: number /* int */;
  haproxyRunning: boolean;
  sslEnabled: boolean;
  version: string;
  checksTotal: number /* int */;
  checksHealthy: number /* int */;
  checksFailed: number /* int */;
  /**
   * PeerSync is populated only when this instance is a non-primary in a fleet.
   */
  peerSync?: PeerSyncStatus;
}
/**
 * PeerSyncStatus surfaces the peer-sync pull-loop state to the dashboard so
 * operators can spot a non-primary that has stopped converging without
 * having to scrape logs. See plan/plan.md Phase 1 hardening item 5.
 */
export interface PeerSyncStatus {
  primaryId: string; // peer id this instance is pulling from
  pullCount: number /* int */; // total pull attempts since startup
  lastPullAt?: number /* int64 */; // unix seconds, 0 if never
  lastSuccessAt?: number /* int64 */; // unix seconds, 0 if never
  lastApplyAt?: number /* int64 */; // unix seconds, 0 if never
  lastError?: string; // empty if last attempt succeeded
}
export interface HealthCheckResp {
  path: string;
}
export interface DeployResp {
  nextBackend: string;
  activeSlot: string;
  balance: string;
}
export interface ProxyResp {
  backend: string;
  staticRoot?: string; // absolute dir served as static files (mutually exclusive with backend)
  self?: boolean; // route to this hz instance's own admin UI
  servedBy?: string; // resolved runtime address HAProxy routes to (static/self: hz's loopback)
  spa?: boolean; // static only: serve index.html for unknown non-asset paths
  healthCheck?: HealthCheckResp;
  internalOnly: boolean;
  deploy?: DeployResp;
  maintenancePageMD5?: string;
  timeouts?: ProxyTimeoutsResp;
}
/**
 * ProxyTimeoutsResp surfaces per-backend HAProxy timeout overrides (seconds).
 * A zero/omitted field means the HAProxy defaults section applies.
 */
export interface ProxyTimeoutsResp {
  connectSeconds?: number /* int */;
  serverSeconds?: number /* int */;
  tunnelSeconds?: number /* int */;
}
export interface InternalDNSResp {
  ip: string;
}
export interface ExternalDNSResp {
  /**
   * IP / IPs are the *resolved* IPs the service currently publishes —
   * either the user's explicit ConfiguredIPs or the host fallback. Use
   * these for display and DNS-status checks.
   */
  ip: string;
  ips?: string[];
  /**
   * ConfiguredIPs is the user-set list. Empty means "use the host's
   * public IP fallback". UI edit forms should use this to populate the
   * IP field — pre-filling with the resolved fallback would silently
   * turn auto-resolution into a per-service static override on save.
   */
  configuredIPs?: string[];
  ttl: number /* int */;
}
export interface ServiceStatus {
  internalDNSUp: boolean; // dnsmasq resolves the primary domain
  internalDNSResolved?: string; // actual IP from dnsmasq
  externalDNSUp: boolean; // 1.1.1.1 resolves the primary domain
  externalDNSResolved?: string; // actual IP from 1.1.1.1
  proxyUp: boolean; // HAProxy backend healthy (from HAProxy socket)
  proxyError?: string; // health check error
  proxyState?: string; // "up", "down", "drain", "maint" (current/single backend)
  proxyNextState?: string; // "up", "down", "drain", "maint" (next slot for deploy)
}
export interface ServiceResp {
  name: string;
  domains: string[];
  internalDNS?: InternalDNSResp;
  externalDNS?: ExternalDNSResp;
  proxy?: ProxyResp;
  integrations?: IntegrationsResp;
  status: ServiceStatus;
}
/**
 * IntegrationsResp mirrors config.Integrations for read/round-trip.
 */
export interface IntegrationsResp {
  metrics?: MetricsResp;
}
/**
 * MetricsResp reports a service's Prometheus metrics integration. Path is the
 * effective path (defaulted to /metrics). Enabled is false when the service opts
 * out (config Disabled) — the write path uses the same flag.
 */
export interface MetricsResp {
  enabled: boolean;
  path?: string;
  bearer?: string;
}
export interface DomainResp {
  domain: string;
  zoneName: string;
  zoneHasSSL: boolean;
  hasZone: boolean;
  serviceName: string;
  hasService: boolean;
  hasInternalDNS: boolean;
  internalIP: string;
  hasExternalDNS: boolean;
  externalIP: string;
  externalIPs?: string[]; // All IPs for round-robin DNS
  dnsmasqResolvedIP: string;
  remoteResolvedIP: string;
  dnsmasqDNSMatch: boolean;
  remoteDNSMatch: boolean;
  hasProxy: boolean;
  proxyBackend: string;
  internalOnly: boolean;
  hasHealthCheck: boolean;
  healthPath: string;
  hasSSLCoverage: boolean;
  certExists: boolean;
  certExpiry: string;
  certDomain: string;
  canEnableHTTPS: boolean;
  neededSubZone: string;
  neededSubZoneDisplay: string;
  canRequestCert: boolean;
  canSyncDNS: boolean;
  coveredBy?: string; // wildcard that covers this domain (e.g., "*.iodesystems.com")
  isRedundant: boolean; // SubZone is redundant with a wildcard on the same zone
  absorbedDomains?: AbsorbedDomain[]; // for wildcards: service domains this covers
}
export interface AbsorbedDomain {
  domain: string;
  service?: string; // service name if bound
}
export interface SSLGapResp {
  domain: string;
  zoneName: string;
  subZone: string;
  display: string;
  reason: string;
}
export interface ZoneSSLResp {
  zoneName: string;
  sslEnabled: boolean;
  configuredDomains: string[];
  actualSANs: string[];
  certExists: boolean;
  certExpiry: string;
  certIssuer: string;
  missingSANs: string[];
  extraSANs: string[];
}
export interface DomainsResponse {
  domains: DomainResp[];
  totalCount: number /* int */;
  intDNSCount: number /* int */;
  extDNSCount: number /* int */;
  httpsCount: number /* int */;
  proxyCount: number /* int */;
  sslGaps: SSLGapResp[];
  zoneSSLStatuses: ZoneSSLResp[];
}
export interface PeerResp {
  name: string;
  publicKey: string;
  allowedIPs: string;
  endpoint?: string;
  latestHandshake?: string;
  transferRx?: string;
  transferTx?: string;
  online: boolean;
  isAdmin: boolean;
  profile: string;
  mfaEnrolled: boolean;
  mfaSessionActive: boolean;
  mfaSessionExpiry?: string;
}
export interface MFAStatusResponse {
  enrolled: boolean;
  sessionActive: boolean;
  sessionExpiry?: string;
  durations: string[];
  provisioningUri?: string; // only during enrollment
}
export interface MFAEnrollResponse {
  ok: boolean;
  provisioningUri: string;
  secret: string;
}
export interface MFAVerifyRequest {
  code: string;
  duration: string; // "2h", "4h", "8h", "forever"
}
export interface MFAVerifyResponse {
  ok: boolean;
  expiry?: string;
}
export interface MFASettingsResponse {
  enabled: boolean;
  durations: string[];
}
export interface AddPeerResponse {
  ok: boolean;
  config: string;
  qrCode: string;
}
export interface PeerConfigResponse {
  ok: boolean;
  config: string;
  qrCode: string;
}
export interface RekeyPeerResponse {
  ok: boolean;
  config: string;
  qrCode: string;
  shareToken: string;
  shareURL: string;
}
export interface ConfigShareResp {
  token: string;
  url: string;
  peerName: string;
}
export interface InviteResp {
  token: string;
  url: string;
}
export interface CreateInviteResponse {
  ok: boolean;
  token: string;
  url: string;
}
export interface ZoneResp {
  name: string;
  zoneId: string;
  sslEnabled: boolean;
  sslEmail?: string;
  subZones: string[];
  providerType?: string;
}
export interface HAProxyResp {
  running: boolean;
  configExists: boolean;
  version: string;
  enabled: boolean;
  httpPort: number /* int */;
  httpsPort: number /* int */;
}
export interface SSLResp {
  enabled: boolean;
  certDir: string;
  haproxyCertDir: string;
}
export interface CheckStatusResp {
  name: string;
  type: string;
  target: string;
  status: string;
  last_check: any /* time.Time */;
  last_error?: string;
  interval: number /* int */;
  enabled: boolean;
  auto_gen: boolean;
}
export interface ConfigResp {
  publicIP: string;
  publicIPOverride?: string;
  publicIPLastChecked?: number /* int64 */; // unix seconds; 0 = never
  publicIPStale: boolean;
  publicIPMaxAge: number /* int */; // staleness threshold, seconds
  localInterface: string;
  dnsmasqEnabled: boolean;
  vpnAdmins: string[];
}
export interface SettingsResponse {
  zones: ZoneResp[];
  haproxy: HAProxyResp;
  ssl: SSLResp;
  checks: CheckStatusResp[];
  config: ConfigResp;
}
/**
 * PublicIPOverrideRequest sets or clears the host's manual public-IP override.
 * Empty Override clears the override (returns to auto-detection).
 */
export interface PublicIPOverrideRequest {
  override: string;
}
/**
 * PublicIPStatusResponse summarizes the host's current public-IP state.
 * Error is set when an immediate refresh attempt failed; the cached PublicIP
 * remains usable (subject to PublicIPStale).
 */
export interface PublicIPStatusResponse {
  publicIP: string;
  publicIPOverride?: string;
  publicIPLastChecked?: number /* int64 */;
  publicIPStale: boolean;
  publicIPMaxAge: number /* int */;
  error?: string;
}
export interface HAProxyConfigPreview {
  config: string;
}
export interface AuthStatusResponse {
  authenticated: boolean;
  method?: string;
  /**
   * Multi-instance HA — populated when this instance is part of a fleet.
   */
  peerId?: string; // local instance identity
  configPrimary?: boolean; // true if this instance is the config primary
  primaryId?: string; // peer id of the config primary (when this instance is non-primary)
}
export interface LoginRequest {
  token: string;
}
export interface LoginResponse {
  ok: boolean;
  invite?: boolean;
  redirect?: string;
}
export interface DeploySlotStatus {
  slot: string;
  backend: string;
  state: string;
}
export interface DeployStatus {
  service: string;
  domain: string;
  domains?: string[];
  active_slot: string;
  balance: string;
  health_check: string;
  current: DeploySlotStatus;
  next: DeploySlotStatus;
  maintenance_page_md5?: string;
}
export interface DeployStateChangeResponse {
  status: string;
  server: string;
  state: string;
}
export interface DeploySwapResponse {
  status: string;
  active_slot: string;
  current: string;
  next: string;
}
export interface ServiceRequest {
  originalName?: string;
  name: string;
  domains: string[];
  internalDNS?: ServiceRequestInternalDNS;
  externalDNS?: ServiceRequestExternalDNS;
  proxy?: ServiceRequestProxy;
  integrations?: ServiceRequestIntegrations;
}
/**
 * ServiceRequestIntegrations carries per-service observability integrations from
 * the write path (API / hz / UI). Full-replace semantics like Proxy/DNS: an edit
 * that omits this clears it.
 */
export interface ServiceRequestIntegrations {
  metrics?: ServiceRequestMetrics;
}
/**
 * ServiceRequestMetrics enables Prometheus metrics discovery for a service.
 * Enabled=false clears the integration. Path defaults to /metrics server-side.
 * Bearer is optional (non-network-isolated endpoints).
 */
export interface ServiceRequestMetrics {
  enabled: boolean;
  path?: string;
  bearer?: string;
}
export interface ServiceRequestInternalDNS {
  ip: string;
}
export interface ServiceRequestExternalDNS {
  ip: string;
  ips?: string[]; // Multiple IPs for round-robin DNS
  ttl: number /* int */;
}
export interface ServiceRequestProxy {
  backend: string;
  staticRoot?: string; // absolute dir served as static files (mutually exclusive with backend)
  static?: boolean; // request static serving; if StaticRoot is empty the server assigns an hz-managed default path
  self?: boolean; // route to this hz instance's own admin UI
  spa?: boolean; // static only: serve index.html for unknown non-asset paths
  healthCheck?: ServiceRequestHealthCheck;
  internalOnly: boolean;
  deploy?: ServiceRequestDeploy;
  timeouts?: ServiceRequestTimeouts;
}
/**
 * ServiceRequestTimeouts carries per-backend HAProxy timeout overrides
 * (seconds) from the service editor. Zero/omitted = inherit defaults.
 */
export interface ServiceRequestTimeouts {
  connectSeconds?: number /* int */;
  serverSeconds?: number /* int */;
  tunnelSeconds?: number /* int */;
}
export interface ServiceRequestDeploy {
  nextBackend: string;
  balance?: string; // "first" or "roundrobin"
}
export interface ServiceRequestHealthCheck {
  path: string;
}
export interface BanRequest {
  ip: string;
  timeout?: number /* int */; // seconds, 0 = permanent
  reason?: string;
}
export interface UnbanRequest {
  ip: string;
}
export interface BanEntry {
  ip: string;
  timeout?: number /* int */;
  createdAt: number /* int64 */;
  expiresAt?: number /* int64 */;
  reason?: string;
  service?: string;
}
export interface BanListResponse {
  bans: BanEntry[];
}
export interface DNSSyncResponse {
  ok: boolean;
  changed: boolean;
}
export interface DNSRecordResp {
  name: string;
  type: string;
  value: string;
  ttl: number /* int */;
  managed: boolean; // declared in Zone.Records (HZ owns it)
}
export interface ZoneRecordsResponse {
  zone: string;
  records: DNSRecordResp[];
}
/**
 * DNSDriftInfoResp describes an out-of-band change detected at a DNS provider
 * that has halted sync.
 */
export interface DNSDriftInfoResp {
  zone: string;
  name: string;
  type: string;
  expected: string[]; // what hz last published
  live: string[]; // what's live at the provider now
  detectedAt: number /* int64 */;
}
export interface DNSDriftStatusResponse {
  blocked: boolean;
  detail?: DNSDriftInfoResp;
}
export interface HostPortEntry {
  port: string;
  proto: string;
  service: string;
  domain?: string;
}
export interface HostPortMapResponse {
  hosts: { [key: string]: HostPortEntry[]};
}
export interface DNSSyncAllResponse {
  ok: boolean;
  updated: number /* int */;
  failed: number /* int */;
}
export interface ToggleAdminResponse {
  ok: boolean;
  isAdmin: boolean;
}
export interface TriggerSyncResponse {
  ok: boolean;
  started: boolean;
}
/**
 * PendingChanges describes config edits made since the last successful full
 * sync, computed by diffing the live config against the snapshot saved at that
 * sync. Shared server-side, so a second admin's unsynced edits surface for
 * everyone — the cue that a Sync is needed and what it will push.
 */
export interface PendingChanges {
  hasPending: boolean;
  count: number /* int */; // number of changed services + zones
  items: PendingItem[];
}
/**
 * PendingItem is one added, removed, or modified service or zone.
 */
export interface PendingItem {
  kind: string; // "service" | "zone"
  name: string;
  change: string; // "added" | "removed" | "modified"
  fields?: FieldChange[]; // changed fields (modified only)
}
/**
 * FieldChange is a single changed field within a modified item, before and
 * after rendered as compact strings for display.
 */
export interface FieldChange {
  path: string;
  before?: string;
  after?: string;
}
export interface RunCheckResponse {
  ok: boolean;
  status: string;
}
export interface CheckResult {
  timestamp: any /* time.Time */;
  status: string;
  latency: number /* int64 */;
  error?: string;
}
export interface CheckHistoryResponse {
  name: string;
  results: CheckResult[];
}
/**
 * AllCheckHistoryEntry is one series (check + its history) in the aggregate
 * history response used by the main /checks page's stacked charts.
 */
export interface AllCheckHistoryEntry {
  name: string;
  results: CheckResult[];
}
export interface AllCheckHistoryResponse {
  series: AllCheckHistoryEntry[];
}
export interface ChecksOverview {
  total: number /* int */;
  healthy: number /* int */;
  failed: number /* int */;
  pending: number /* int */;
}
export interface DomainSSLAddRequest {
  domain: string;
}
export interface DomainSSLAddResponse {
  ok: boolean;
  zone: string;
  subZone: string;
}
export interface DomainSSLRemoveRequest {
  domain: string;
}
export interface ServiceIntegration {
  name: string;
  token: string;
  baseURL: string;
  hasDeploy: boolean;
  hasStatic: boolean; // static-folder service: site upload available
}
export interface HAFleetPeer {
  id: string;
  wgAddr: string;
  primary?: boolean;
  online?: boolean;
  lastSyncAt?: string;
  lastSyncErr?: string;
  iptables_summary?: IPTablesSummary; // peer's local rule classification counts
}
/**
 * IPTablesSummary mirrors internal/iptables.Summary for the wire format.
 * Kept here so the apitypes package is self-contained and tygo can emit it.
 */
export interface IPTablesSummary {
  expected: number /* int */;
  stale: number /* int */;
  blessed: number /* int */;
  unknown: number /* int */;
}
export interface HAStatusResponse {
  peerId: string;
  configPrimary: boolean;
  peers: HAFleetPeer[];
}
export interface HACreateJoinTokenRequest {
  peerId: string;
  topology: string; // "same-subnet" or "site-to-site"
  /**
   * Site-to-site fields
   */
  remoteEndpoint?: string; // e.g. "1.2.3.4:51830"
  vpnRange?: string; // e.g. "10.0.2.0/24"
}
export interface HACreateJoinTokenResponse {
  ok: boolean;
  token: string;
  oneLiner: string;
}
export interface HAJoinCompleteRequest {
  peer_id: string;
  wg_addr: string;
  s2s_pubkey?: string;
  vpn_pubkey: string;
}
export interface ComponentHealth {
  name: string; // "wireguard", "haproxy", "dnsmasq", "letsencrypt"
  installed: boolean; // binary on PATH
  config_exists: boolean; // component config file present
  enabled: boolean; // systemd unit enabled at boot
  running: boolean; // systemd unit currently active
  version?: string;
  extras?: { [key: string]: any}; // component-specific facts
  errors?: string[];
}
export interface SystemHealthResponse {
  components: ComponentHealth[];
  ip_forwarding: boolean;
  ip_forwarding_error?: string;
  horizon_unit_installed: boolean;
  horizon_enabled: boolean;
  horizon_running: boolean;
}
export interface CPUMetric {
  user: number /* uint64 */;
  nice: number /* uint64 */;
  system: number /* uint64 */;
  idle: number /* uint64 */;
  iowait: number /* uint64 */;
  irq: number /* uint64 */;
  softirq: number /* uint64 */;
  steal: number /* uint64 */;
  cores: number /* int */;
}
export interface MemoryMetric {
  total_bytes: number /* uint64 */;
  available_bytes: number /* uint64 */;
  used_bytes: number /* uint64 */;
  swap_total_bytes: number /* uint64 */;
  swap_used_bytes: number /* uint64 */;
}
export interface NetworkIface {
  iface: string;
  rx_bytes: number /* uint64 */;
  tx_bytes: number /* uint64 */;
}
export interface DiskMetric {
  mount: string;
  fs_type: string;
  total_bytes: number /* uint64 */;
  free_bytes: number /* uint64 */;
  used_bytes: number /* uint64 */;
}
export interface SystemMetricsResponse {
  ts: number /* int64 */;
  cpu: CPUMetric;
  memory: MemoryMetric;
  network: NetworkIface[];
  disks: DiskMetric[];
  load1: number /* float64 */;
  load5: number /* float64 */;
  load15: number /* float64 */;
  uptime_seconds: number /* float64 */;
}
