// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go

/**
 * Error response
 */
export interface ErrorResponse {
  error: string;
}
/**
 * OK response (used by many mutation endpoints)
 */
export interface OKResponse {
  ok: boolean;
}
export interface DashboardResponse {
  serviceCount: number /* int */;
  domainCount: number /* int */;
  zoneCount: number /* int */;
  peerCount: number /* int */;
  haproxyRunning: boolean;
  sslEnabled: boolean;
  version: string;
  checksTotal: number /* int */;
  checksHealthy: number /* int */;
  checksFailed: number /* int */;
  /**
   * PeerSync is populated only when this instance is a non-primary in a fleet.
   */
  peerSync?: PeerSyncStatus;
}
/**
 * PeerSyncStatus surfaces the peer-sync pull-loop state to the dashboard so
 * operators can spot a non-primary that has stopped converging without
 * having to scrape logs. See plan/plan.md Phase 1 hardening item 5.
 */
export interface PeerSyncStatus {
  primaryId: string; // peer id this instance is pulling from
  pullCount: number /* int */; // total pull attempts since startup
  lastPullAt?: number /* int64 */; // unix seconds, 0 if never
  lastSuccessAt?: number /* int64 */; // unix seconds, 0 if never
  lastApplyAt?: number /* int64 */; // unix seconds, 0 if never
  lastError?: string; // empty if last attempt succeeded
}
export interface HealthCheckResp {
  path: string;
}
export interface DeployResp {
  nextBackend: string;
  activeSlot: string;
  balance: string;
}
export interface ProxyResp {
  backend: string;
  healthCheck?: HealthCheckResp;
  internalOnly: boolean;
  deploy?: DeployResp;
  maintenancePageMD5?: string;
}
export interface InternalDNSResp {
  ip: string;
}
export interface ExternalDNSResp {
  ip: string;
  ips?: string[]; // All IPs for round-robin DNS
  ttl: number /* int */;
}
export interface ServiceStatus {
  internalDNSUp: boolean; // dnsmasq resolves the primary domain
  internalDNSResolved?: string; // actual IP from dnsmasq
  externalDNSUp: boolean; // 1.1.1.1 resolves the primary domain
  externalDNSResolved?: string; // actual IP from 1.1.1.1
  proxyUp: boolean; // HAProxy backend healthy (from HAProxy socket)
  proxyError?: string; // health check error
  proxyState?: string; // "up", "down", "drain", "maint" (current/single backend)
  proxyNextState?: string; // "up", "down", "drain", "maint" (next slot for deploy)
}
export interface ServiceResp {
  name: string;
  domains: string[];
  internalDNS?: InternalDNSResp;
  externalDNS?: ExternalDNSResp;
  proxy?: ProxyResp;
  status: ServiceStatus;
}
export interface DomainResp {
  domain: string;
  zoneName: string;
  zoneHasSSL: boolean;
  hasZone: boolean;
  serviceName: string;
  hasService: boolean;
  hasInternalDNS: boolean;
  internalIP: string;
  hasExternalDNS: boolean;
  externalIP: string;
  externalIPs?: string[]; // All IPs for round-robin DNS
  dnsmasqResolvedIP: string;
  remoteResolvedIP: string;
  dnsmasqDNSMatch: boolean;
  remoteDNSMatch: boolean;
  hasProxy: boolean;
  proxyBackend: string;
  internalOnly: boolean;
  hasHealthCheck: boolean;
  healthPath: string;
  hasSSLCoverage: boolean;
  certExists: boolean;
  certExpiry: string;
  certDomain: string;
  canEnableHTTPS: boolean;
  neededSubZone: string;
  neededSubZoneDisplay: string;
  canRequestCert: boolean;
  canSyncDNS: boolean;
  coveredBy?: string; // wildcard that covers this domain (e.g., "*.iodesystems.com")
  isRedundant: boolean; // SubZone is redundant with a wildcard on the same zone
  absorbedDomains?: AbsorbedDomain[]; // for wildcards: service domains this covers
}
export interface AbsorbedDomain {
  domain: string;
  service?: string; // service name if bound
}
export interface SSLGapResp {
  domain: string;
  zoneName: string;
  subZone: string;
  display: string;
  reason: string;
}
export interface ZoneSSLResp {
  zoneName: string;
  sslEnabled: boolean;
  configuredDomains: string[];
  actualSANs: string[];
  certExists: boolean;
  certExpiry: string;
  certIssuer: string;
  missingSANs: string[];
  extraSANs: string[];
}
export interface DomainsResponse {
  domains: DomainResp[];
  totalCount: number /* int */;
  intDNSCount: number /* int */;
  extDNSCount: number /* int */;
  httpsCount: number /* int */;
  proxyCount: number /* int */;
  sslGaps: SSLGapResp[];
  zoneSSLStatuses: ZoneSSLResp[];
}
export interface PeerResp {
  name: string;
  publicKey: string;
  allowedIPs: string;
  endpoint?: string;
  latestHandshake?: string;
  transferRx?: string;
  transferTx?: string;
  online: boolean;
  isAdmin: boolean;
  profile: string;
  mfaEnrolled: boolean;
  mfaSessionActive: boolean;
  mfaSessionExpiry?: string;
}
export interface MFAStatusResponse {
  enrolled: boolean;
  sessionActive: boolean;
  sessionExpiry?: string;
  durations: string[];
  provisioningUri?: string; // only during enrollment
}
export interface MFAEnrollResponse {
  ok: boolean;
  provisioningUri: string;
  secret: string;
}
export interface MFAVerifyRequest {
  code: string;
  duration: string; // "2h", "4h", "8h", "forever"
}
export interface MFAVerifyResponse {
  ok: boolean;
  expiry?: string;
}
export interface MFASettingsResponse {
  enabled: boolean;
  durations: string[];
}
export interface AddPeerResponse {
  ok: boolean;
  config: string;
  qrCode: string;
}
export interface PeerConfigResponse {
  ok: boolean;
  config: string;
  qrCode: string;
}
export interface RekeyPeerResponse {
  ok: boolean;
  config: string;
  qrCode: string;
  shareToken: string;
  shareURL: string;
}
export interface ConfigShareResp {
  token: string;
  url: string;
  peerName: string;
}
export interface InviteResp {
  token: string;
  url: string;
}
export interface CreateInviteResponse {
  ok: boolean;
  token: string;
  url: string;
}
export interface ZoneResp {
  name: string;
  zoneId: string;
  sslEnabled: boolean;
  sslEmail?: string;
  subZones: string[];
  providerType?: string;
}
export interface HAProxyResp {
  running: boolean;
  configExists: boolean;
  version: string;
  enabled: boolean;
  httpPort: number /* int */;
  httpsPort: number /* int */;
}
export interface SSLResp {
  enabled: boolean;
  certDir: string;
  haproxyCertDir: string;
}
export interface CheckStatusResp {
  name: string;
  type: string;
  target: string;
  status: string;
  last_check: any /* time.Time */;
  last_error?: string;
  interval: number /* int */;
  enabled: boolean;
  auto_gen: boolean;
}
export interface ConfigResp {
  publicIP: string;
  localInterface: string;
  dnsmasqEnabled: boolean;
  vpnAdmins: string[];
}
export interface SettingsResponse {
  zones: ZoneResp[];
  haproxy: HAProxyResp;
  ssl: SSLResp;
  checks: CheckStatusResp[];
  config: ConfigResp;
}
export interface HAProxyConfigPreview {
  config: string;
}
export interface AuthStatusResponse {
  authenticated: boolean;
  method?: string;
  /**
   * Multi-instance HA — populated when this instance is part of a fleet.
   */
  peerId?: string; // local instance identity
  configPrimary?: boolean; // true if this instance is the config primary
  primaryId?: string; // peer id of the config primary (when this instance is non-primary)
}
export interface LoginRequest {
  token: string;
}
export interface LoginResponse {
  ok: boolean;
  invite?: boolean;
  redirect?: string;
}
export interface DeploySlotStatus {
  slot: string;
  backend: string;
  state: string;
}
export interface DeployStatus {
  service: string;
  domain: string;
  domains?: string[];
  active_slot: string;
  balance: string;
  health_check: string;
  current: DeploySlotStatus;
  next: DeploySlotStatus;
  maintenance_page_md5?: string;
}
export interface DeployStateChangeResponse {
  status: string;
  server: string;
  state: string;
}
export interface DeploySwapResponse {
  status: string;
  active_slot: string;
  current: string;
  next: string;
}
export interface ServiceRequest {
  originalName?: string;
  name: string;
  domains: string[];
  internalDNS?: ServiceRequestInternalDNS;
  externalDNS?: ServiceRequestExternalDNS;
  proxy?: ServiceRequestProxy;
}
export interface ServiceRequestInternalDNS {
  ip: string;
}
export interface ServiceRequestExternalDNS {
  ip: string;
  ips?: string[]; // Multiple IPs for round-robin DNS
  ttl: number /* int */;
}
export interface ServiceRequestProxy {
  backend: string;
  healthCheck?: ServiceRequestHealthCheck;
  internalOnly: boolean;
  deploy?: ServiceRequestDeploy;
}
export interface ServiceRequestDeploy {
  nextBackend: string;
  balance?: string; // "first" or "roundrobin"
}
export interface ServiceRequestHealthCheck {
  path: string;
}
export interface BanRequest {
  ip: string;
  timeout?: number /* int */; // seconds, 0 = permanent
  reason?: string;
}
export interface UnbanRequest {
  ip: string;
}
export interface BanEntry {
  ip: string;
  timeout?: number /* int */;
  createdAt: number /* int64 */;
  expiresAt?: number /* int64 */;
  reason?: string;
  service?: string;
}
export interface BanListResponse {
  bans: BanEntry[];
}
export interface DNSSyncResponse {
  ok: boolean;
  changed: boolean;
}
export interface DNSSyncAllResponse {
  ok: boolean;
  updated: number /* int */;
  failed: number /* int */;
}
export interface ToggleAdminResponse {
  ok: boolean;
  isAdmin: boolean;
}
export interface TriggerSyncResponse {
  ok: boolean;
  started: boolean;
}
export interface RunCheckResponse {
  ok: boolean;
  status: string;
}
export interface CheckResult {
  timestamp: any /* time.Time */;
  status: string;
  latency: number /* int64 */;
  error?: string;
}
export interface CheckHistoryResponse {
  name: string;
  results: CheckResult[];
}
export interface ChecksOverview {
  total: number /* int */;
  healthy: number /* int */;
  failed: number /* int */;
  pending: number /* int */;
}
export interface DomainSSLAddRequest {
  domain: string;
}
export interface DomainSSLAddResponse {
  ok: boolean;
  zone: string;
  subZone: string;
}
export interface DomainSSLRemoveRequest {
  domain: string;
}
export interface ServiceIntegration {
  name: string;
  token: string;
  baseURL: string;
  hasDeploy: boolean;
}
export interface HAFleetPeer {
  id: string;
  wgAddr: string;
  primary?: boolean;
  online?: boolean;
  lastSyncAt?: string;
  lastSyncErr?: string;
  iptables_summary?: IPTablesSummary; // peer's local rule classification counts
}
/**
 * IPTablesSummary mirrors internal/iptables.Summary for the wire format.
 * Kept here so the apitypes package is self-contained and tygo can emit it.
 */
export interface IPTablesSummary {
  expected: number /* int */;
  stale: number /* int */;
  blessed: number /* int */;
  unknown: number /* int */;
}
export interface HAStatusResponse {
  peerId: string;
  configPrimary: boolean;
  peers: HAFleetPeer[];
}
export interface HACreateJoinTokenRequest {
  peerId: string;
  topology: string; // "same-subnet" or "site-to-site"
  /**
   * Site-to-site fields
   */
  remoteEndpoint?: string; // e.g. "1.2.3.4:51830"
  vpnRange?: string; // e.g. "10.0.2.0/24"
}
export interface HACreateJoinTokenResponse {
  ok: boolean;
  token: string;
  oneLiner: string;
}
export interface HAJoinCompleteRequest {
  peer_id: string;
  wg_addr: string;
  s2s_pubkey?: string;
  vpn_pubkey: string;
}
export interface ComponentHealth {
  name: string; // "wireguard", "haproxy", "dnsmasq", "letsencrypt"
  installed: boolean; // binary on PATH
  config_exists: boolean; // component config file present
  enabled: boolean; // systemd unit enabled at boot
  running: boolean; // systemd unit currently active
  version?: string;
  extras?: { [key: string]: any}; // component-specific facts
  errors?: string[];
}
export interface SystemHealthResponse {
  components: ComponentHealth[];
  ip_forwarding: boolean;
  ip_forwarding_error?: string;
  horizon_unit_installed: boolean;
  horizon_enabled: boolean;
  horizon_running: boolean;
}
