/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectRouteImport } from './routes/$project'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BansRouteImport } from './routes/bans'
import { Route as ChecksRouteImport } from './routes/checks'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as DriftRouteImport } from './routes/drift'
import { Route as HostsRouteImport } from './routes/hosts'
import { Route as MfaRouteImport } from './routes/mfa'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as PortsRouteImport } from './routes/ports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SegmentsRouteImport } from './routes/segments'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VpnRouteImport } from './routes/vpn'
import { Route as ProjectIndexRouteImport } from './routes/$project.index'
import { Route as ProjectConfigRouteImport } from './routes/$project.config'
import { Route as ProjectDomainsRouteImport } from './routes/$project.domains'
import { Route as ProjectMachinesRouteImport } from './routes/$project.machines'
import { Route as ProjectSegmentsRouteImport } from './routes/$project.segments'
import { Route as ProjectServicesRouteImport } from './routes/$project.services'
import { Route as DnsIndexRouteImport } from './routes/dns.index'
import { Route as DnsZoneRouteImport } from './routes/dns.$zone'
import { Route as MachinesIndexRouteImport } from './routes/machines.index'
import { Route as MachinesMachineRouteImport } from './routes/machines.$machine'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectRoute = ProjectRouteImport.update({
  id: '/$project',
  path: '/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BansRoute = BansRouteImport.update({
  id: '/bans',
  path: '/bans',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecksRoute = ChecksRouteImport.update({
  id: '/checks',
  path: '/checks',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const DriftRoute = DriftRouteImport.update({
  id: '/drift',
  path: '/drift',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsRoute = HostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaRoute = MfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const PortsRoute = PortsRouteImport.update({
  id: '/ports',
  path: '/ports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentsRoute = SegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VpnRoute = VpnRouteImport.update({
  id: '/vpn',
  path: '/vpn',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectIndexRoute = ProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectRoute,
} as any)
const ProjectConfigRoute = ProjectConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => ProjectRoute,
} as any)
const ProjectDomainsRoute = ProjectDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => ProjectRoute,
} as any)
const ProjectMachinesRoute = ProjectMachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => ProjectRoute,
} as any)
const ProjectSegmentsRoute = ProjectSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => ProjectRoute,
} as any)
const ProjectServicesRoute = ProjectServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => ProjectRoute,
} as any)
const DnsIndexRoute = DnsIndexRouteImport.update({
  id: '/dns/',
  path: '/dns/',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsZoneRoute = DnsZoneRouteImport.update({
  id: '/dns/$zone',
  path: '/dns/$zone',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesIndexRoute = MachinesIndexRouteImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesMachineRoute = MachinesMachineRouteImport.update({
  id: '/machines/$machine',
  path: '/machines/$machine',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$project': typeof ProjectRouteWithChildren
  '/account': typeof AccountRoute
  '/bans': typeof BansRoute
  '/checks': typeof ChecksRoute
  '/config': typeof ConfigRoute
  '/dashboard': typeof DashboardRoute
  '/domains': typeof DomainsRoute
  '/drift': typeof DriftRoute
  '/hosts': typeof HostsRoute
  '/mfa': typeof MfaRoute
  '/observability': typeof ObservabilityRoute
  '/ports': typeof PortsRoute
  '/projects': typeof ProjectsRoute
  '/segments': typeof SegmentsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/vpn': typeof VpnRoute
  '/$project/config': typeof ProjectConfigRoute
  '/$project/domains': typeof ProjectDomainsRoute
  '/$project/machines': typeof ProjectMachinesRoute
  '/$project/segments': typeof ProjectSegmentsRoute
  '/$project/services': typeof ProjectServicesRoute
  '/dns/$zone': typeof DnsZoneRoute
  '/machines/$machine': typeof MachinesMachineRoute
  '/$project/': typeof ProjectIndexRoute
  '/dns/': typeof DnsIndexRoute
  '/machines/': typeof MachinesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bans': typeof BansRoute
  '/checks': typeof ChecksRoute
  '/config': typeof ConfigRoute
  '/dashboard': typeof DashboardRoute
  '/domains': typeof DomainsRoute
  '/drift': typeof DriftRoute
  '/hosts': typeof HostsRoute
  '/mfa': typeof MfaRoute
  '/observability': typeof ObservabilityRoute
  '/ports': typeof PortsRoute
  '/projects': typeof ProjectsRoute
  '/segments': typeof SegmentsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/vpn': typeof VpnRoute
  '/$project/config': typeof ProjectConfigRoute
  '/$project/domains': typeof ProjectDomainsRoute
  '/$project/machines': typeof ProjectMachinesRoute
  '/$project/segments': typeof ProjectSegmentsRoute
  '/$project/services': typeof ProjectServicesRoute
  '/dns/$zone': typeof DnsZoneRoute
  '/machines/$machine': typeof MachinesMachineRoute
  '/$project': typeof ProjectIndexRoute
  '/dns': typeof DnsIndexRoute
  '/machines': typeof MachinesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$project': typeof ProjectRouteWithChildren
  '/account': typeof AccountRoute
  '/bans': typeof BansRoute
  '/checks': typeof ChecksRoute
  '/config': typeof ConfigRoute
  '/dashboard': typeof DashboardRoute
  '/domains': typeof DomainsRoute
  '/drift': typeof DriftRoute
  '/hosts': typeof HostsRoute
  '/mfa': typeof MfaRoute
  '/observability': typeof ObservabilityRoute
  '/ports': typeof PortsRoute
  '/projects': typeof ProjectsRoute
  '/segments': typeof SegmentsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/vpn': typeof VpnRoute
  '/$project/config': typeof ProjectConfigRoute
  '/$project/domains': typeof ProjectDomainsRoute
  '/$project/machines': typeof ProjectMachinesRoute
  '/$project/segments': typeof ProjectSegmentsRoute
  '/$project/services': typeof ProjectServicesRoute
  '/dns/$zone': typeof DnsZoneRoute
  '/machines/$machine': typeof MachinesMachineRoute
  '/$project/': typeof ProjectIndexRoute
  '/dns/': typeof DnsIndexRoute
  '/machines/': typeof MachinesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$project'
    | '/account'
    | '/bans'
    | '/checks'
    | '/config'
    | '/dashboard'
    | '/domains'
    | '/drift'
    | '/hosts'
    | '/mfa'
    | '/observability'
    | '/ports'
    | '/projects'
    | '/segments'
    | '/services'
    | '/settings'
    | '/vpn'
    | '/$project/config'
    | '/$project/domains'
    | '/$project/machines'
    | '/$project/segments'
    | '/$project/services'
    | '/dns/$zone'
    | '/machines/$machine'
    | '/$project/'
    | '/dns/'
    | '/machines/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/bans'
    | '/checks'
    | '/config'
    | '/dashboard'
    | '/domains'
    | '/drift'
    | '/hosts'
    | '/mfa'
    | '/observability'
    | '/ports'
    | '/projects'
    | '/segments'
    | '/services'
    | '/settings'
    | '/vpn'
    | '/$project/config'
    | '/$project/domains'
    | '/$project/machines'
    | '/$project/segments'
    | '/$project/services'
    | '/dns/$zone'
    | '/machines/$machine'
    | '/$project'
    | '/dns'
    | '/machines'
  id:
    | '__root__'
    | '/'
    | '/$project'
    | '/account'
    | '/bans'
    | '/checks'
    | '/config'
    | '/dashboard'
    | '/domains'
    | '/drift'
    | '/hosts'
    | '/mfa'
    | '/observability'
    | '/ports'
    | '/projects'
    | '/segments'
    | '/services'
    | '/settings'
    | '/vpn'
    | '/$project/config'
    | '/$project/domains'
    | '/$project/machines'
    | '/$project/segments'
    | '/$project/services'
    | '/dns/$zone'
    | '/machines/$machine'
    | '/$project/'
    | '/dns/'
    | '/machines/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectRoute: typeof ProjectRouteWithChildren
  AccountRoute: typeof AccountRoute
  BansRoute: typeof BansRoute
  ChecksRoute: typeof ChecksRoute
  ConfigRoute: typeof ConfigRoute
  DashboardRoute: typeof DashboardRoute
  DomainsRoute: typeof DomainsRoute
  DriftRoute: typeof DriftRoute
  HostsRoute: typeof HostsRoute
  MfaRoute: typeof MfaRoute
  ObservabilityRoute: typeof ObservabilityRoute
  PortsRoute: typeof PortsRoute
  ProjectsRoute: typeof ProjectsRoute
  SegmentsRoute: typeof SegmentsRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  VpnRoute: typeof VpnRoute
  DnsZoneRoute: typeof DnsZoneRoute
  MachinesMachineRoute: typeof MachinesMachineRoute
  DnsIndexRoute: typeof DnsIndexRoute
  MachinesIndexRoute: typeof MachinesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$project': {
      id: '/$project'
      path: '/$project'
      fullPath: '/$project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bans': {
      id: '/bans'
      path: '/bans'
      fullPath: '/bans'
      preLoaderRoute: typeof BansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checks': {
      id: '/checks'
      path: '/checks'
      fullPath: '/checks'
      preLoaderRoute: typeof ChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drift': {
      id: '/drift'
      path: '/drift'
      fullPath: '/drift'
      preLoaderRoute: typeof DriftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts': {
      id: '/hosts'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof HostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa': {
      id: '/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof MfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ports': {
      id: '/ports'
      path: '/ports'
      fullPath: '/ports'
      preLoaderRoute: typeof PortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segments': {
      id: '/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof SegmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vpn': {
      id: '/vpn'
      path: '/vpn'
      fullPath: '/vpn'
      preLoaderRoute: typeof VpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$project/': {
      id: '/$project/'
      path: '/'
      fullPath: '/$project/'
      preLoaderRoute: typeof ProjectIndexRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/$project/config': {
      id: '/$project/config'
      path: '/config'
      fullPath: '/$project/config'
      preLoaderRoute: typeof ProjectConfigRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/$project/domains': {
      id: '/$project/domains'
      path: '/domains'
      fullPath: '/$project/domains'
      preLoaderRoute: typeof ProjectDomainsRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/$project/machines': {
      id: '/$project/machines'
      path: '/machines'
      fullPath: '/$project/machines'
      preLoaderRoute: typeof ProjectMachinesRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/$project/segments': {
      id: '/$project/segments'
      path: '/segments'
      fullPath: '/$project/segments'
      preLoaderRoute: typeof ProjectSegmentsRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/$project/services': {
      id: '/$project/services'
      path: '/services'
      fullPath: '/$project/services'
      preLoaderRoute: typeof ProjectServicesRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/dns/': {
      id: '/dns/'
      path: '/dns'
      fullPath: '/dns/'
      preLoaderRoute: typeof DnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns/$zone': {
      id: '/dns/$zone'
      path: '/dns/$zone'
      fullPath: '/dns/$zone'
      preLoaderRoute: typeof DnsZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/': {
      id: '/machines/'
      path: '/machines'
      fullPath: '/machines/'
      preLoaderRoute: typeof MachinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/$machine': {
      id: '/machines/$machine'
      path: '/machines/$machine'
      fullPath: '/machines/$machine'
      preLoaderRoute: typeof MachinesMachineRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectRouteChildren {
  ProjectConfigRoute: typeof ProjectConfigRoute
  ProjectDomainsRoute: typeof ProjectDomainsRoute
  ProjectMachinesRoute: typeof ProjectMachinesRoute
  ProjectSegmentsRoute: typeof ProjectSegmentsRoute
  ProjectServicesRoute: typeof ProjectServicesRoute
  ProjectIndexRoute: typeof ProjectIndexRoute
}

const ProjectRouteChildren: ProjectRouteChildren = {
  ProjectConfigRoute: ProjectConfigRoute,
  ProjectDomainsRoute: ProjectDomainsRoute,
  ProjectMachinesRoute: ProjectMachinesRoute,
  ProjectSegmentsRoute: ProjectSegmentsRoute,
  ProjectServicesRoute: ProjectServicesRoute,
  ProjectIndexRoute: ProjectIndexRoute,
}

const ProjectRouteWithChildren =
  ProjectRoute._addFileChildren(ProjectRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectRoute: ProjectRouteWithChildren,
  AccountRoute: AccountRoute,
  BansRoute: BansRoute,
  ChecksRoute: ChecksRoute,
  ConfigRoute: ConfigRoute,
  DashboardRoute: DashboardRoute,
  DomainsRoute: DomainsRoute,
  DriftRoute: DriftRoute,
  HostsRoute: HostsRoute,
  MfaRoute: MfaRoute,
  ObservabilityRoute: ObservabilityRoute,
  PortsRoute: PortsRoute,
  ProjectsRoute: ProjectsRoute,
  SegmentsRoute: SegmentsRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  VpnRoute: VpnRoute,
  DnsZoneRoute: DnsZoneRoute,
  MachinesMachineRoute: MachinesMachineRoute,
  DnsIndexRoute: DnsIndexRoute,
  MachinesIndexRoute: MachinesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
