/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BansRouteImport } from './routes/bans'
import { Route as ChecksRouteImport } from './routes/checks'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DomainsRouteImport } from './routes/domains'
import { Route as DriftRouteImport } from './routes/drift'
import { Route as HostsRouteImport } from './routes/hosts'
import { Route as MfaRouteImport } from './routes/mfa'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as ObservabilityRouteImport } from './routes/observability'
import { Route as PortsRouteImport } from './routes/ports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as SegmentsRouteImport } from './routes/segments'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VpnRouteImport } from './routes/vpn'
import { Route as DnsIndexRouteImport } from './routes/dns.index'
import { Route as DnsZoneRouteImport } from './routes/dns.$zone'
import { Route as MachinesIndexRouteImport } from './routes/machines.index'
import { Route as MachinesMachineRouteImport } from './routes/machines.$machine'
import { Route as PIndexRouteImport } from './routes/p.index'
import { Route as PProjectRouteImport } from './routes/p.$project'
import { Route as PProjectIndexRouteImport } from './routes/p.$project.index'
import { Route as PProjectConfigRouteImport } from './routes/p.$project.config'
import { Route as PProjectDomainsRouteImport } from './routes/p.$project.domains'
import { Route as PProjectMachinesRouteImport } from './routes/p.$project.machines'
import { Route as PProjectNetworkRouteImport } from './routes/p.$project.network'
import { Route as PProjectServicesRouteImport } from './routes/p.$project.services'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BansRoute = BansRouteImport.update({
  id: '/bans',
  path: '/bans',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecksRoute = ChecksRouteImport.update({
  id: '/checks',
  path: '/checks',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DomainsRoute = DomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => rootRouteImport,
} as any)
const DriftRoute = DriftRouteImport.update({
  id: '/drift',
  path: '/drift',
  getParentRoute: () => rootRouteImport,
} as any)
const HostsRoute = HostsRouteImport.update({
  id: '/hosts',
  path: '/hosts',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaRoute = MfaRouteImport.update({
  id: '/mfa',
  path: '/mfa',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const ObservabilityRoute = ObservabilityRouteImport.update({
  id: '/observability',
  path: '/observability',
  getParentRoute: () => rootRouteImport,
} as any)
const PortsRoute = PortsRouteImport.update({
  id: '/ports',
  path: '/ports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const SegmentsRoute = SegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VpnRoute = VpnRouteImport.update({
  id: '/vpn',
  path: '/vpn',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsIndexRoute = DnsIndexRouteImport.update({
  id: '/dns/',
  path: '/dns/',
  getParentRoute: () => rootRouteImport,
} as any)
const DnsZoneRoute = DnsZoneRouteImport.update({
  id: '/dns/$zone',
  path: '/dns/$zone',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesIndexRoute = MachinesIndexRouteImport.update({
  id: '/machines/',
  path: '/machines/',
  getParentRoute: () => rootRouteImport,
} as any)
const MachinesMachineRoute = MachinesMachineRouteImport.update({
  id: '/machines/$machine',
  path: '/machines/$machine',
  getParentRoute: () => rootRouteImport,
} as any)
const PIndexRoute = PIndexRouteImport.update({
  id: '/p/',
  path: '/p/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectRoute = PProjectRouteImport.update({
  id: '/p/$project',
  path: '/p/$project',
  getParentRoute: () => rootRouteImport,
} as any)
const PProjectIndexRoute = PProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PProjectRoute,
} as any)
const PProjectConfigRoute = PProjectConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => PProjectRoute,
} as any)
const PProjectDomainsRoute = PProjectDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => PProjectRoute,
} as any)
const PProjectMachinesRoute = PProjectMachinesRouteImport.update({
  id: '/machines',
  path: '/machines',
  getParentRoute: () => PProjectRoute,
} as any)
const PProjectNetworkRoute = PProjectNetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => PProjectRoute,
} as any)
const PProjectServicesRoute = PProjectServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PProjectRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/bans': typeof BansRoute
  '/checks': typeof ChecksRoute
  '/config': typeof ConfigRoute
  '/dashboard': typeof DashboardRoute
  '/domains': typeof DomainsRoute
  '/drift': typeof DriftRoute
  '/hosts': typeof HostsRoute
  '/mfa': typeof MfaRoute
  '/network': typeof NetworkRoute
  '/observability': typeof ObservabilityRoute
  '/ports': typeof PortsRoute
  '/projects': typeof ProjectsRoute
  '/segments': typeof SegmentsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/vpn': typeof VpnRoute
  '/dns/$zone': typeof DnsZoneRoute
  '/machines/$machine': typeof MachinesMachineRoute
  '/p/$project': typeof PProjectRouteWithChildren
  '/dns/': typeof DnsIndexRoute
  '/machines/': typeof MachinesIndexRoute
  '/p/': typeof PIndexRoute
  '/p/$project/config': typeof PProjectConfigRoute
  '/p/$project/domains': typeof PProjectDomainsRoute
  '/p/$project/machines': typeof PProjectMachinesRoute
  '/p/$project/network': typeof PProjectNetworkRoute
  '/p/$project/services': typeof PProjectServicesRoute
  '/p/$project/': typeof PProjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/bans': typeof BansRoute
  '/checks': typeof ChecksRoute
  '/config': typeof ConfigRoute
  '/dashboard': typeof DashboardRoute
  '/domains': typeof DomainsRoute
  '/drift': typeof DriftRoute
  '/hosts': typeof HostsRoute
  '/mfa': typeof MfaRoute
  '/network': typeof NetworkRoute
  '/observability': typeof ObservabilityRoute
  '/ports': typeof PortsRoute
  '/projects': typeof ProjectsRoute
  '/segments': typeof SegmentsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/vpn': typeof VpnRoute
  '/dns/$zone': typeof DnsZoneRoute
  '/machines/$machine': typeof MachinesMachineRoute
  '/dns': typeof DnsIndexRoute
  '/machines': typeof MachinesIndexRoute
  '/p': typeof PIndexRoute
  '/p/$project/config': typeof PProjectConfigRoute
  '/p/$project/domains': typeof PProjectDomainsRoute
  '/p/$project/machines': typeof PProjectMachinesRoute
  '/p/$project/network': typeof PProjectNetworkRoute
  '/p/$project/services': typeof PProjectServicesRoute
  '/p/$project': typeof PProjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/account': typeof AccountRoute
  '/bans': typeof BansRoute
  '/checks': typeof ChecksRoute
  '/config': typeof ConfigRoute
  '/dashboard': typeof DashboardRoute
  '/domains': typeof DomainsRoute
  '/drift': typeof DriftRoute
  '/hosts': typeof HostsRoute
  '/mfa': typeof MfaRoute
  '/network': typeof NetworkRoute
  '/observability': typeof ObservabilityRoute
  '/ports': typeof PortsRoute
  '/projects': typeof ProjectsRoute
  '/segments': typeof SegmentsRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/vpn': typeof VpnRoute
  '/dns/$zone': typeof DnsZoneRoute
  '/machines/$machine': typeof MachinesMachineRoute
  '/p/$project': typeof PProjectRouteWithChildren
  '/dns/': typeof DnsIndexRoute
  '/machines/': typeof MachinesIndexRoute
  '/p/': typeof PIndexRoute
  '/p/$project/config': typeof PProjectConfigRoute
  '/p/$project/domains': typeof PProjectDomainsRoute
  '/p/$project/machines': typeof PProjectMachinesRoute
  '/p/$project/network': typeof PProjectNetworkRoute
  '/p/$project/services': typeof PProjectServicesRoute
  '/p/$project/': typeof PProjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/account'
    | '/bans'
    | '/checks'
    | '/config'
    | '/dashboard'
    | '/domains'
    | '/drift'
    | '/hosts'
    | '/mfa'
    | '/network'
    | '/observability'
    | '/ports'
    | '/projects'
    | '/segments'
    | '/services'
    | '/settings'
    | '/vpn'
    | '/dns/$zone'
    | '/machines/$machine'
    | '/p/$project'
    | '/dns/'
    | '/machines/'
    | '/p/'
    | '/p/$project/config'
    | '/p/$project/domains'
    | '/p/$project/machines'
    | '/p/$project/network'
    | '/p/$project/services'
    | '/p/$project/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/account'
    | '/bans'
    | '/checks'
    | '/config'
    | '/dashboard'
    | '/domains'
    | '/drift'
    | '/hosts'
    | '/mfa'
    | '/network'
    | '/observability'
    | '/ports'
    | '/projects'
    | '/segments'
    | '/services'
    | '/settings'
    | '/vpn'
    | '/dns/$zone'
    | '/machines/$machine'
    | '/dns'
    | '/machines'
    | '/p'
    | '/p/$project/config'
    | '/p/$project/domains'
    | '/p/$project/machines'
    | '/p/$project/network'
    | '/p/$project/services'
    | '/p/$project'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/account'
    | '/bans'
    | '/checks'
    | '/config'
    | '/dashboard'
    | '/domains'
    | '/drift'
    | '/hosts'
    | '/mfa'
    | '/network'
    | '/observability'
    | '/ports'
    | '/projects'
    | '/segments'
    | '/services'
    | '/settings'
    | '/vpn'
    | '/dns/$zone'
    | '/machines/$machine'
    | '/p/$project'
    | '/dns/'
    | '/machines/'
    | '/p/'
    | '/p/$project/config'
    | '/p/$project/domains'
    | '/p/$project/machines'
    | '/p/$project/network'
    | '/p/$project/services'
    | '/p/$project/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AccountRoute: typeof AccountRoute
  BansRoute: typeof BansRoute
  ChecksRoute: typeof ChecksRoute
  ConfigRoute: typeof ConfigRoute
  DashboardRoute: typeof DashboardRoute
  DomainsRoute: typeof DomainsRoute
  DriftRoute: typeof DriftRoute
  HostsRoute: typeof HostsRoute
  MfaRoute: typeof MfaRoute
  NetworkRoute: typeof NetworkRoute
  ObservabilityRoute: typeof ObservabilityRoute
  PortsRoute: typeof PortsRoute
  ProjectsRoute: typeof ProjectsRoute
  SegmentsRoute: typeof SegmentsRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  VpnRoute: typeof VpnRoute
  DnsZoneRoute: typeof DnsZoneRoute
  MachinesMachineRoute: typeof MachinesMachineRoute
  PProjectRoute: typeof PProjectRouteWithChildren
  DnsIndexRoute: typeof DnsIndexRoute
  MachinesIndexRoute: typeof MachinesIndexRoute
  PIndexRoute: typeof PIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bans': {
      id: '/bans'
      path: '/bans'
      fullPath: '/bans'
      preLoaderRoute: typeof BansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checks': {
      id: '/checks'
      path: '/checks'
      fullPath: '/checks'
      preLoaderRoute: typeof ChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domains': {
      id: '/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof DomainsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drift': {
      id: '/drift'
      path: '/drift'
      fullPath: '/drift'
      preLoaderRoute: typeof DriftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hosts': {
      id: '/hosts'
      path: '/hosts'
      fullPath: '/hosts'
      preLoaderRoute: typeof HostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa': {
      id: '/mfa'
      path: '/mfa'
      fullPath: '/mfa'
      preLoaderRoute: typeof MfaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/observability': {
      id: '/observability'
      path: '/observability'
      fullPath: '/observability'
      preLoaderRoute: typeof ObservabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ports': {
      id: '/ports'
      path: '/ports'
      fullPath: '/ports'
      preLoaderRoute: typeof PortsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/segments': {
      id: '/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof SegmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vpn': {
      id: '/vpn'
      path: '/vpn'
      fullPath: '/vpn'
      preLoaderRoute: typeof VpnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns/': {
      id: '/dns/'
      path: '/dns'
      fullPath: '/dns/'
      preLoaderRoute: typeof DnsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dns/$zone': {
      id: '/dns/$zone'
      path: '/dns/$zone'
      fullPath: '/dns/$zone'
      preLoaderRoute: typeof DnsZoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/': {
      id: '/machines/'
      path: '/machines'
      fullPath: '/machines/'
      preLoaderRoute: typeof MachinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machines/$machine': {
      id: '/machines/$machine'
      path: '/machines/$machine'
      fullPath: '/machines/$machine'
      preLoaderRoute: typeof MachinesMachineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/': {
      id: '/p/'
      path: '/p'
      fullPath: '/p/'
      preLoaderRoute: typeof PIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$project': {
      id: '/p/$project'
      path: '/p/$project'
      fullPath: '/p/$project'
      preLoaderRoute: typeof PProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$project/': {
      id: '/p/$project/'
      path: '/'
      fullPath: '/p/$project/'
      preLoaderRoute: typeof PProjectIndexRouteImport
      parentRoute: typeof PProjectRoute
    }
    '/p/$project/config': {
      id: '/p/$project/config'
      path: '/config'
      fullPath: '/p/$project/config'
      preLoaderRoute: typeof PProjectConfigRouteImport
      parentRoute: typeof PProjectRoute
    }
    '/p/$project/domains': {
      id: '/p/$project/domains'
      path: '/domains'
      fullPath: '/p/$project/domains'
      preLoaderRoute: typeof PProjectDomainsRouteImport
      parentRoute: typeof PProjectRoute
    }
    '/p/$project/machines': {
      id: '/p/$project/machines'
      path: '/machines'
      fullPath: '/p/$project/machines'
      preLoaderRoute: typeof PProjectMachinesRouteImport
      parentRoute: typeof PProjectRoute
    }
    '/p/$project/network': {
      id: '/p/$project/network'
      path: '/network'
      fullPath: '/p/$project/network'
      preLoaderRoute: typeof PProjectNetworkRouteImport
      parentRoute: typeof PProjectRoute
    }
    '/p/$project/services': {
      id: '/p/$project/services'
      path: '/services'
      fullPath: '/p/$project/services'
      preLoaderRoute: typeof PProjectServicesRouteImport
      parentRoute: typeof PProjectRoute
    }
  }
}

interface PProjectRouteChildren {
  PProjectConfigRoute: typeof PProjectConfigRoute
  PProjectDomainsRoute: typeof PProjectDomainsRoute
  PProjectMachinesRoute: typeof PProjectMachinesRoute
  PProjectNetworkRoute: typeof PProjectNetworkRoute
  PProjectServicesRoute: typeof PProjectServicesRoute
  PProjectIndexRoute: typeof PProjectIndexRoute
}

const PProjectRouteChildren: PProjectRouteChildren = {
  PProjectConfigRoute: PProjectConfigRoute,
  PProjectDomainsRoute: PProjectDomainsRoute,
  PProjectMachinesRoute: PProjectMachinesRoute,
  PProjectNetworkRoute: PProjectNetworkRoute,
  PProjectServicesRoute: PProjectServicesRoute,
  PProjectIndexRoute: PProjectIndexRoute,
}

const PProjectRouteWithChildren = PProjectRoute._addFileChildren(
  PProjectRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AccountRoute: AccountRoute,
  BansRoute: BansRoute,
  ChecksRoute: ChecksRoute,
  ConfigRoute: ConfigRoute,
  DashboardRoute: DashboardRoute,
  DomainsRoute: DomainsRoute,
  DriftRoute: DriftRoute,
  HostsRoute: HostsRoute,
  MfaRoute: MfaRoute,
  NetworkRoute: NetworkRoute,
  ObservabilityRoute: ObservabilityRoute,
  PortsRoute: PortsRoute,
  ProjectsRoute: ProjectsRoute,
  SegmentsRoute: SegmentsRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  VpnRoute: VpnRoute,
  DnsZoneRoute: DnsZoneRoute,
  MachinesMachineRoute: MachinesMachineRoute,
  PProjectRoute: PProjectRouteWithChildren,
  DnsIndexRoute: DnsIndexRoute,
  MachinesIndexRoute: MachinesIndexRoute,
  PIndexRoute: PIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
