package dnsmasq

import (
	"bufio"
	"context"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"time"
)

type DNSMasq struct {
	mu         sync.Mutex
	configPath string
	hostsPath  string
	interfaces []string
	upstream   []string
}

func New(configPath, hostsPath string, interfaces []string, upstream []string) *DNSMasq {
	return &DNSMasq{
		configPath: configPath,
		hostsPath:  hostsPath,
		interfaces: interfaces,
		upstream:   upstream,
	}
}

func (d *DNSMasq) WriteConfig() error {
	d.mu.Lock()
	defer d.mu.Unlock()

	dir := filepath.Dir(d.configPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create config directory: %w", err)
	}

	var config strings.Builder

	config.WriteString("# WireGuard VPN dnsmasq configuration\n")
	config.WriteString("# Generated by wg-self-serve\n\n")

	config.WriteString("# Required for systemd-resolved compatibility\n")
	config.WriteString("bind-dynamic\n")
	for _, iface := range d.interfaces {
		config.WriteString(fmt.Sprintf("interface=%s\n", iface))
	}
	config.WriteString("\n")

	config.WriteString("# Upstream DNS servers\n")
	for _, dns := range d.upstream {
		config.WriteString(fmt.Sprintf("server=%s\n", dns))
	}
	config.WriteString("\n")

	config.WriteString("# Don't use /etc/resolv.conf\n")
	config.WriteString("no-resolv\n\n")

	config.WriteString("# Cache settings\n")
	config.WriteString("cache-size=1000\n\n")

	// Include hosts/address file if it's separate from the main config
	if d.hostsPath != "" && d.hostsPath != d.configPath {
		config.WriteString("# DNS address mappings\n")
		config.WriteString(fmt.Sprintf("conf-file=%s\n", d.hostsPath))
	}

	if err := os.WriteFile(d.configPath, []byte(config.String()), 0644); err != nil {
		return fmt.Errorf("failed to write config: %w", err)
	}

	if _, err := os.Stat(d.hostsPath); os.IsNotExist(err) {
		if err := os.WriteFile(d.hostsPath, []byte("# VPN DNS mappings\n# Generated by wg-self-serve\n# Format: address=/hostname/ip\n"), 0644); err != nil {
			return fmt.Errorf("failed to create hosts file: %w", err)
		}
	}

	return nil
}

func (d *DNSMasq) GetMappings() (map[string]string, error) {
	d.mu.Lock()
	defer d.mu.Unlock()

	mappings := make(map[string]string)

	file, err := os.Open(d.hostsPath)
	if err != nil {
		if os.IsNotExist(err) {
			return mappings, nil
		}
		return nil, err
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Parse address=/hostname/ip format
		if strings.HasPrefix(line, "address=/") {
			parts := strings.Split(strings.TrimPrefix(line, "address=/"), "/")
			if len(parts) >= 2 {
				hostname := parts[0]
				ip := parts[1]
				mappings[hostname] = ip
			}
		}
	}

	return mappings, scanner.Err()
}

func (d *DNSMasq) SetMappings(mappings map[string]string) error {
	d.mu.Lock()
	defer d.mu.Unlock()

	var hosts strings.Builder
	hosts.WriteString("# VPN DNS mappings\n")
	hosts.WriteString("# Generated by wg-self-serve\n\n")

	for hostname, ip := range mappings {
		hosts.WriteString(fmt.Sprintf("address=/%s/%s\n", hostname, ip))
	}

	if err := os.WriteFile(d.hostsPath, []byte(hosts.String()), 0644); err != nil {
		return fmt.Errorf("failed to write hosts file: %w", err)
	}

	return nil
}

func (d *DNSMasq) AddMapping(hostname, ip string) error {
	mappings, err := d.GetMappings()
	if err != nil {
		return err
	}

	mappings[hostname] = ip
	return d.SetMappings(mappings)
}

func (d *DNSMasq) RemoveMapping(hostname string) error {
	mappings, err := d.GetMappings()
	if err != nil {
		return err
	}

	delete(mappings, hostname)
	return d.SetMappings(mappings)
}

func (d *DNSMasq) Reload() error {
	if err := d.ensureServiceUnit(); err != nil {
		return err
	}
	return systemctlWithJournal("restart", "dnsmasq")
}

func (d *DNSMasq) Start() error {
	if err := d.ensureServiceUnit(); err != nil {
		return err
	}
	return systemctlWithJournal("start", "dnsmasq")
}

// ensureServiceUnit creates dnsmasq.service if it doesn't exist.
// Ubuntu's dnsmasq package uses sysv init scripts and relies on
// systemd-sysv-generator, which may not run when installed via
// a transient systemd-run service.
func (d *DNSMasq) ensureServiceUnit() error {
	servicePath := "/etc/systemd/system/dnsmasq.service"

	// If a system-provided unit exists (not ours), use it
	existingContent := ""
	if out, err := exec.Command("systemctl", "cat", "dnsmasq.service").CombinedOutput(); err == nil {
		if !strings.Contains(string(out), "managed by homelab-horizon") {
			return nil
		}
		existingContent = string(out)
	}

	// Check dnsmasq binary exists
	dnsmasqBin, err := exec.LookPath("dnsmasq")
	if err != nil {
		return fmt.Errorf("dnsmasq binary not found — install it first")
	}

	serviceContent := fmt.Sprintf(`[Unit]
Description=dnsmasq - managed by homelab-horizon
After=network.target

[Service]
Type=simple
ExecStart=%s -k -C %s
ExecReload=/bin/kill -HUP $MAINPID
Restart=on-failure

[Install]
WantedBy=multi-user.target
`, dnsmasqBin, d.configPath)

	// Skip if content hasn't changed
	if strings.Contains(existingContent, strings.TrimSpace(serviceContent)) {
		return nil
	}

	// Create/update our service unit
	cmd := exec.Command("systemd-run", "--pipe", "--wait", "--service-type=oneshot",
		"bash", "-c", fmt.Sprintf("cat > %s && systemctl daemon-reload", servicePath))
	cmd.Stdin = strings.NewReader(serviceContent)
	if out, err := cmd.CombinedOutput(); err != nil {
		return fmt.Errorf("failed to create dnsmasq.service: %v — %s", err, strings.TrimSpace(string(out)))
	}

	return nil
}

// systemctlWithJournal runs a systemctl command and, on failure, pulls recent
// journal lines for the unit so the caller gets a useful error message.
// Uses systemd-run to escape ProtectSystem=strict sandbox.
func systemctlWithJournal(action, unit string) error {
	cmd := exec.Command("systemd-run", "--pipe", "--wait", "--service-type=oneshot",
		"systemctl", action, unit)
	if out, err := cmd.CombinedOutput(); err != nil {
		// Grab last 10 journal lines for context
		journal := exec.Command("systemd-run", "--pipe", "--wait", "--service-type=oneshot",
			"journalctl", "-u", unit, "-n", "10", "--no-pager", "-o", "cat")
		journalOut, _ := journal.CombinedOutput()
		detail := strings.TrimSpace(string(out))
		if len(journalOut) > 0 {
			detail += "\n" + strings.TrimSpace(string(journalOut))
		}
		if detail == "" {
			detail = err.Error()
		}
		return fmt.Errorf("%s %s failed: %s", action, unit, detail)
	}
	return nil
}

type Status struct {
	Running           bool
	Enabled           bool
	ConfigExists      bool
	Error             string
	MissingInterfaces []string // Configured interfaces not found in dnsmasq config
	// ListenAddresses is the set of listen-address= IPs from the config file.
	// Callers compare these against cfg.LocalInterface to detect drift — if
	// dnsmasq's config says "bind 192.168.1.10" but LocalInterface is now
	// 192.168.2.15, service-name resolution against the new IP fails even
	// though dnsmasq is "running".
	ListenAddresses []string
}

func (d *DNSMasq) Status() Status {
	status := Status{}

	cmd := exec.Command("systemctl", "is-active", "dnsmasq")
	if err := cmd.Run(); err == nil {
		status.Running = true
	}

	cmd = exec.Command("systemctl", "is-enabled", "dnsmasq")
	if err := cmd.Run(); err == nil {
		status.Enabled = true
	}

	if _, err := os.Stat(d.configPath); err == nil {
		status.ConfigExists = true
	}

	// Check if all configured interfaces are present in the config file
	if status.ConfigExists {
		status.MissingInterfaces = d.checkMissingInterfaces()
		status.ListenAddresses = d.readListenAddresses()
	}

	return status
}

// readListenAddresses extracts every `listen-address=<ip>` line from the
// dnsmasq config file. Deliberately doesn't touch the kernel or query ss(8) —
// this is cheap, self-contained, and the config is the source of truth for
// what dnsmasq will bind to on the next reload.
func (d *DNSMasq) readListenAddresses() []string {
	data, err := os.ReadFile(d.configPath)
	if err != nil {
		return nil
	}
	var addrs []string
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "listen-address=") {
			addr := strings.TrimPrefix(line, "listen-address=")
			addr = strings.TrimSpace(addr)
			if addr != "" {
				addrs = append(addrs, addr)
			}
		}
	}
	return addrs
}

// checkMissingInterfaces compares configured interfaces against what's in the config file
func (d *DNSMasq) checkMissingInterfaces() []string {
	data, err := os.ReadFile(d.configPath)
	if err != nil {
		return nil
	}

	// Collect interface= lines from the config file
	onDisk := make(map[string]bool)
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "interface=") {
			onDisk[strings.TrimPrefix(line, "interface=")] = true
		}
	}

	var missing []string
	for _, iface := range d.interfaces {
		if !onDisk[iface] {
			missing = append(missing, iface)
		}
	}
	return missing
}

func (d *DNSMasq) UpdateUpstream(servers []string) {
	d.mu.Lock()
	defer d.mu.Unlock()
	d.upstream = servers
}

// ResolveWith resolves a hostname against a specific DNS server
func ResolveWith(hostname, dnsServer string) (string, error) {
	if !strings.Contains(dnsServer, ":") {
		dnsServer = dnsServer + ":53"
	}

	resolver := &net.Resolver{
		PreferGo: true,
		Dial: func(ctx context.Context, network, address string) (net.Conn, error) {
			d := net.Dialer{Timeout: 2 * time.Second}
			return d.DialContext(ctx, "udp", dnsServer)
		},
	}

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	ips, err := resolver.LookupIP(ctx, "ip4", hostname)
	if err != nil {
		return "", err
	}
	if len(ips) == 0 {
		return "", fmt.Errorf("no A record found")
	}
	return ips[0].String(), nil
}

// ResolveAllWith resolves multiple hostnames in parallel against a DNS server
func ResolveAllWith(hostnames []string, dnsServer string) map[string]string {
	results := make(map[string]string)
	var mu sync.Mutex
	var wg sync.WaitGroup

	for _, h := range hostnames {
		wg.Add(1)
		go func(hostname string) {
			defer wg.Done()
			ip, err := ResolveWith(hostname, dnsServer)
			mu.Lock()
			if err != nil {
				results[hostname] = ""
			} else {
				results[hostname] = ip
			}
			mu.Unlock()
		}(h)
	}

	wg.Wait()
	return results
}
