package dnsmasq

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGetMappings_ParsesAddressFormat(t *testing.T) {
	tempDir := t.TempDir()
	hostsPath := filepath.Join(tempDir, "hosts")

	content := `# VPN DNS mappings
# Generated by wg-self-serve

address=/app.example.com/192.168.1.50
address=/api.example.com/192.168.1.51
address=/grafana.local/10.0.0.100

# This is a comment
address=/with-dash.example.com/192.168.1.52
`
	if err := os.WriteFile(hostsPath, []byte(content), 0644); err != nil {
		t.Fatalf("failed to write test hosts file: %v", err)
	}

	d := New("/tmp/dnsmasq.conf", hostsPath, nil, nil)
	mappings, err := d.GetMappings()
	if err != nil {
		t.Fatalf("GetMappings() error = %v", err)
	}

	expected := map[string]string{
		"app.example.com":       "192.168.1.50",
		"api.example.com":       "192.168.1.51",
		"grafana.local":         "10.0.0.100",
		"with-dash.example.com": "192.168.1.52",
	}

	for hostname, wantIP := range expected {
		t.Run(hostname, func(t *testing.T) {
			got, exists := mappings[hostname]
			if !exists {
				t.Errorf("mapping for %s not found", hostname)
				return
			}
			if got != wantIP {
				t.Errorf("mappings[%s] = %s, want %s", hostname, got, wantIP)
			}
		})
	}

	if len(mappings) != 4 {
		t.Errorf("expected 4 mappings, got %d", len(mappings))
	}
}

func TestGetMappings_EmptyFile(t *testing.T) {
	tempDir := t.TempDir()
	hostsPath := filepath.Join(tempDir, "hosts")

	content := `# Just comments
# No actual mappings
`
	if err := os.WriteFile(hostsPath, []byte(content), 0644); err != nil {
		t.Fatalf("failed to write test hosts file: %v", err)
	}

	d := New("/tmp/dnsmasq.conf", hostsPath, nil, nil)
	mappings, err := d.GetMappings()
	if err != nil {
		t.Fatalf("GetMappings() error = %v", err)
	}

	if len(mappings) != 0 {
		t.Errorf("expected 0 mappings, got %d", len(mappings))
	}
}

func TestGetMappings_NonExistentFile(t *testing.T) {
	d := New("/tmp/dnsmasq.conf", "/nonexistent/path/hosts", nil, nil)
	mappings, err := d.GetMappings()
	if err != nil {
		t.Fatalf("GetMappings() should not error for nonexistent file, got %v", err)
	}

	if len(mappings) != 0 {
		t.Errorf("expected 0 mappings for nonexistent file, got %d", len(mappings))
	}
}

func TestSetMappings(t *testing.T) {
	tempDir := t.TempDir()
	hostsPath := filepath.Join(tempDir, "hosts")

	d := New("/tmp/dnsmasq.conf", hostsPath, nil, nil)

	input := map[string]string{
		"app.example.com": "192.168.1.50",
		"api.example.com": "192.168.1.51",
	}

	if err := d.SetMappings(input); err != nil {
		t.Fatalf("SetMappings() error = %v", err)
	}

	got, err := d.GetMappings()
	if err != nil {
		t.Fatalf("GetMappings() error = %v", err)
	}

	if len(got) != 2 {
		t.Errorf("expected 2 mappings, got %d", len(got))
	}

	for hostname, ip := range input {
		if got[hostname] != ip {
			t.Errorf("mappings[%s] = %s, want %s", hostname, got[hostname], ip)
		}
	}
}

func TestAddMapping(t *testing.T) {
	tempDir := t.TempDir()
	hostsPath := filepath.Join(tempDir, "hosts")

	if err := os.WriteFile(hostsPath, []byte(""), 0644); err != nil {
		t.Fatalf("failed to write test hosts file: %v", err)
	}

	d := New("/tmp/dnsmasq.conf", hostsPath, nil, nil)

	if err := d.AddMapping("new.example.com", "10.0.0.1"); err != nil {
		t.Fatalf("AddMapping() error = %v", err)
	}

	mappings, _ := d.GetMappings()
	if mappings["new.example.com"] != "10.0.0.1" {
		t.Errorf("AddMapping failed: got %s, want 10.0.0.1", mappings["new.example.com"])
	}
}

func TestRemoveMapping(t *testing.T) {
	tempDir := t.TempDir()
	hostsPath := filepath.Join(tempDir, "hosts")

	content := `address=/keep.example.com/192.168.1.1
address=/remove.example.com/192.168.1.2
`
	if err := os.WriteFile(hostsPath, []byte(content), 0644); err != nil {
		t.Fatalf("failed to write test hosts file: %v", err)
	}

	d := New("/tmp/dnsmasq.conf", hostsPath, nil, nil)

	if err := d.RemoveMapping("remove.example.com"); err != nil {
		t.Fatalf("RemoveMapping() error = %v", err)
	}

	mappings, _ := d.GetMappings()
	if _, exists := mappings["remove.example.com"]; exists {
		t.Error("RemoveMapping failed: mapping still exists")
	}
	if mappings["keep.example.com"] != "192.168.1.1" {
		t.Error("RemoveMapping removed wrong mapping")
	}
}

func TestWriteConfig(t *testing.T) {
	tempDir := t.TempDir()
	configPath := filepath.Join(tempDir, "dnsmasq.conf")
	hostsPath := filepath.Join(tempDir, "hosts")

	d := New(configPath, hostsPath, []string{"wg0", "eth0"}, []string{"8.8.8.8", "1.1.1.1"})

	if err := d.WriteConfig(); err != nil {
		t.Fatalf("WriteConfig() error = %v", err)
	}

	content, err := os.ReadFile(configPath)
	if err != nil {
		t.Fatalf("failed to read config file: %v", err)
	}

	configStr := string(content)

	expectedDirectives := []string{
		"interface=wg0",
		"interface=eth0",
		"server=8.8.8.8",
		"server=1.1.1.1",
		"bind-dynamic",
		"no-resolv",
		"no-hosts",
		"cache-size=1000",
	}

	for _, directive := range expectedDirectives {
		if !strings.Contains(configStr, directive) {
			t.Errorf("config should contain %q", directive)
		}
	}

	if _, err := os.Stat(hostsPath); os.IsNotExist(err) {
		t.Error("hosts file should be created")
	}
}

func TestNew(t *testing.T) {
	d := New("/etc/dnsmasq.d/wg.conf", "/etc/dnsmasq.d/hosts", []string{"wg0"}, []string{"8.8.8.8"})

	if d == nil {
		t.Fatal("New() returned nil")
	}
}

func TestUpdateUpstream(t *testing.T) {
	tempDir := t.TempDir()
	configPath := filepath.Join(tempDir, "dnsmasq.conf")
	hostsPath := filepath.Join(tempDir, "hosts")

	d := New(configPath, hostsPath, nil, []string{"8.8.8.8"})
	d.UpdateUpstream([]string{"1.1.1.1", "9.9.9.9"})

	if err := d.WriteConfig(); err != nil {
		t.Fatalf("WriteConfig() error = %v", err)
	}

	content, _ := os.ReadFile(configPath)
	configStr := string(content)

	if !strings.Contains(configStr, "server=1.1.1.1") {
		t.Error("config should contain updated upstream 1.1.1.1")
	}
	if !strings.Contains(configStr, "server=9.9.9.9") {
		t.Error("config should contain updated upstream 9.9.9.9")
	}
}

// The local domain is what makes a bare host record reachable through an
// upstream resolver: a single-label query is never forwarded, because there is
// no domain to forward it for.
func TestWriteConfigLocalDomain(t *testing.T) {
	dir := t.TempDir()
	d := New(filepath.Join(dir, "hz.conf"), filepath.Join(dir, "hosts.conf"), []string{"wg0"}, []string{"1.1.1.1"})

	// Off by default: no domain directives at all.
	if err := d.WriteConfig(); err != nil {
		t.Fatalf("write: %v", err)
	}
	body, _ := os.ReadFile(filepath.Join(dir, "hz.conf"))
	if strings.Contains(string(body), "expand-hosts") {
		t.Error("expand-hosts appeared without a domain configured")
	}

	d.SetLocalDomain("LAN")
	if err := d.WriteConfig(); err != nil {
		t.Fatalf("write: %v", err)
	}
	body, _ = os.ReadFile(filepath.Join(dir, "hz.conf"))
	got := string(body)

	for _, want := range []string{"domain=lan", "local=/lan/"} {
		if !strings.Contains(got, want) {
			t.Errorf("config missing %q:\n%s", want, got)
		}
	}
	// Deliberately NOT expand-hosts: it applies to hosts-file and DHCP names
	// and leaves host-record alone, so relying on it produced a config that
	// looked right and answered nothing for host.domain. The expansion is done
	// per record instead — see TestRecordsExpandBareNames.
	if strings.Contains(got, "expand-hosts") {
		t.Error("expand-hosts does not apply to host-record; it should not be emitted")
	}
}

// The expansion that actually works: both names on one host-record, so a bare
// label and its qualified form cannot drift apart.
func TestRecordsExpandBareNames(t *testing.T) {
	dir := t.TempDir()
	hosts := filepath.Join(dir, "hosts.conf")
	d := New(filepath.Join(dir, "hz.conf"), hosts, []string{"wg0"}, []string{"1.1.1.1"})
	d.SetLocalDomain("lan")

	if err := d.SetRecords([]Record{
		{Name: "desktop", IP: "192.168.1.76"},
		// Already qualified: nothing to expand.
		{Name: "wiki.example.com", IP: "192.168.1.50"},
		// A wildcard is a different directive and is not expanded.
		{Name: "lab.example.com", IP: "192.168.1.90", Wildcard: true},
	}); err != nil {
		t.Fatalf("write: %v", err)
	}

	body, _ := os.ReadFile(hosts)
	got := string(body)

	if !strings.Contains(got, "host-record=desktop,desktop.lan,192.168.1.76") {
		t.Errorf("bare name was not expanded:\n%s", got)
	}
	if !strings.Contains(got, "host-record=wiki.example.com,192.168.1.50") {
		t.Errorf("a qualified name should not gain a domain:\n%s", got)
	}
	if !strings.Contains(got, "address=/lab.example.com/192.168.1.90") {
		t.Errorf("wildcard directive wrong:\n%s", got)
	}

	// Without a domain, a bare name stays bare.
	d.SetLocalDomain("")
	if err := d.SetRecords([]Record{{Name: "desktop", IP: "192.168.1.76"}}); err != nil {
		t.Fatalf("write: %v", err)
	}
	body, _ = os.ReadFile(hosts)
	if !strings.Contains(string(body), "host-record=desktop,192.168.1.76") {
		t.Errorf("no domain should mean no expansion:\n%s", body)
	}
}

// Clearing it must remove the directives, not leave a stale domain behind.
func TestWriteConfigLocalDomainCleared(t *testing.T) {
	dir := t.TempDir()
	d := New(filepath.Join(dir, "hz.conf"), filepath.Join(dir, "hosts.conf"), []string{"wg0"}, []string{"1.1.1.1"})

	d.SetLocalDomain("lan")
	_ = d.WriteConfig()
	d.SetLocalDomain("")
	_ = d.WriteConfig()

	body, _ := os.ReadFile(filepath.Join(dir, "hz.conf"))
	if strings.Contains(string(body), "domain=") || strings.Contains(string(body), "expand-hosts") {
		t.Errorf("clearing the domain left directives behind:\n%s", body)
	}
}
