package dnsmasq

// This file is the PURE half of the package: desired state in, bytes out. It
// reads no files, runs no commands, looks at no clock and consults no
// environment — everything it needs arrives as an argument, so the config a
// machine would get can be computed, diffed and tested without being on that
// machine and without being root.

import (
	"bufio"
	"fmt"
	"sort"
	"strings"
)

// ConfigInput is the whole of what dnsmasq.conf is computed from: no other
// input reaches RenderConfig. Two machines given the same ConfigInput get the
// same bytes, which is what makes "what would change on box X" answerable
// without touching box X.
type ConfigInput struct {
	// ConfigPath and HostsPath are interpolated, never opened. The conf-file
	// include is emitted only when the two differ — see RenderConfig.
	ConfigPath string
	HostsPath  string

	Interfaces []string // bound with bind-dynamic, in the order given
	Upstream   []string // server= lines, in the order given

	// LocalDomain, when set, is the domain hz claims as its own. Empty emits
	// no domain directives at all. Expansion of bare names is done per record
	// in RenderHosts, not here — see the comment on the directives below.
	LocalDomain string
}

// HostsInput is the whole of what the records file is computed from.
//
// Records arrive as the complete desired set. The file is not read back to
// build it: hz derives every record from its config (config.DeriveDNSRecords),
// and the file says so in its own header. GetMappings exists for the other
// direction — seeing what is actually on the box — and nothing in the render
// path calls it.
type HostsInput struct {
	Records []Record

	// LocalDomain is appended to bare (single-label) host records so one
	// record answers for both "desktop" and "desktop.<domain>". Empty disables
	// the expansion.
	LocalDomain string
}

// Record is one answer this resolver serves.
type Record struct {
	Name string
	IP   string
	// Wildcard answers for every subdomain of Name as well.
	Wildcard bool
	// Comment is written above the record so the generated file explains
	// itself to whoever reads it on the box.
	Comment string
}

// initialHostsFile is what a missing records file is seeded with, so the
// conf-file include in dnsmasq.conf always points at something that exists —
// dnsmasq refuses to start on a missing include.
const initialHostsFile = "# VPN DNS mappings\n# Generated by wg-self-serve\n# Format: address=/hostname/ip\n"

// RenderConfig returns the contents of dnsmasq.conf.
func RenderConfig(in ConfigInput) string {
	var config strings.Builder

	config.WriteString("# WireGuard VPN dnsmasq configuration\n")
	config.WriteString("# Generated by wg-self-serve\n\n")

	config.WriteString("# Required for systemd-resolved compatibility\n")
	config.WriteString("bind-dynamic\n")
	for _, iface := range in.Interfaces {
		fmt.Fprintf(&config, "interface=%s\n", iface)
	}
	config.WriteString("\n")

	config.WriteString("# Upstream DNS servers\n")
	for _, dns := range in.Upstream {
		fmt.Fprintf(&config, "server=%s\n", dns)
	}
	config.WriteString("\n")

	config.WriteString("# Don't use /etc/resolv.conf\n")
	config.WriteString("no-resolv\n\n")

	// A local domain exists because a resolver upstream of hz will not forward
	// a single-label name at all — there is no domain to forward it for — so a
	// bare "desktop" only ever resolves for clients pointed straight at hz.
	//
	// The expansion itself is done by writing both names onto the record (see
	// RenderHosts), NOT by expand-hosts: that directive applies to hosts-file
	// and DHCP names and leaves host-record entries alone, which is a
	// difference worth stating because the config looks like it should work.
	//
	// domain= is still right for DHCP-derived names, and local=/domain/ stops
	// hz forwarding its own domain upstream, so an unknown name in it fails
	// immediately instead of after a round trip to a public resolver that has
	// never heard of it.
	if in.LocalDomain != "" {
		config.WriteString("# Local domain (expansion is done per-record, see wg-hosts.conf)\n")
		fmt.Fprintf(&config, "domain=%s\n", in.LocalDomain)
		fmt.Fprintf(&config, "local=/%s/\n\n", in.LocalDomain)
	}

	// Ignore /etc/hosts entirely — our records come from the conf-file below.
	// Otherwise a stray /etc/hosts line (e.g. a loopback entry for a service
	// domain) gets served to every VPN/LAN client and overrides our address=
	// mapping, pointing clients at 127.0.0.1 instead of the horizon host.
	config.WriteString("# Ignore /etc/hosts — records come from conf-file below\n")
	config.WriteString("no-hosts\n\n")

	config.WriteString("# Cache settings\n")
	config.WriteString("cache-size=1000\n\n")

	// Include hosts/address file if it's separate from the main config
	if in.HostsPath != "" && in.HostsPath != in.ConfigPath {
		config.WriteString("# DNS address mappings\n")
		fmt.Fprintf(&config, "conf-file=%s\n", in.HostsPath)
	}

	return config.String()
}

// RenderHosts returns the contents of the records file.
//
// Two directives, because they mean different things. `address=/name/ip`
// matches the name and everything beneath it, which is right for a service
// domain fronting a vhost. `host-record=name,ip` is an exact A record and also
// gives dnsmasq the reverse lookup, which is right for a host — a machine
// called "desktop" should not also be answering for "anything.desktop".
func RenderHosts(in HostsInput) string {
	sorted := make([]Record, len(in.Records))
	copy(sorted, in.Records)
	// Deterministic order: the file is regenerated on every service change,
	// and map iteration order would make every write look like a diff to
	// anyone watching the box.
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	var hosts strings.Builder
	hosts.WriteString("# DNS records served by homelab-horizon.\n")
	hosts.WriteString("# Generated — edits here are overwritten on the next sync.\n")
	hosts.WriteString("# Add records via the DNS page or /api/v1/dns/local.\n\n")

	for _, r := range sorted {
		if r.Comment != "" {
			fmt.Fprintf(&hosts, "# %s\n", strings.ReplaceAll(r.Comment, "\n", " "))
		}
		if r.Wildcard {
			fmt.Fprintf(&hosts, "address=/%s/%s\n", r.Name, r.IP)
			continue
		}
		// host-record takes several names for one address, so a bare label and
		// its domain-qualified form are one record rather than two that could
		// drift apart.
		names := r.Name
		if in.LocalDomain != "" && !strings.Contains(r.Name, ".") {
			names = r.Name + "," + r.Name + "." + in.LocalDomain
		}
		fmt.Fprintf(&hosts, "host-record=%s,%s\n", names, r.IP)
	}

	return hosts.String()
}

// ParseMappings extracts name→IP from the text of a records file. It is the
// inverse of RenderHosts, as far as an inverse exists: wildcard and exact
// records collapse to the same map, and comments are dropped.
//
// Kept pure and separate from the file read (GetMappings) so drift between what
// hz would write and what is actually on a box can be computed from two strings
// — including in a process that is not on that box.
func ParseMappings(body string) map[string]string {
	mappings := make(map[string]string)

	scanner := bufio.NewScanner(strings.NewReader(body))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}

		// Both directives this package writes. Reading only address=/ would
		// make every host-record invisible to callers that diff the file
		// against what they expect to be served.
		if strings.HasPrefix(line, "address=/") {
			parts := strings.Split(strings.TrimPrefix(line, "address=/"), "/")
			if len(parts) >= 2 {
				mappings[parts[0]] = parts[1]
			}
			continue
		}
		if strings.HasPrefix(line, "host-record=") {
			parts := strings.Split(strings.TrimPrefix(line, "host-record="), ",")
			if len(parts) >= 2 {
				mappings[strings.TrimSpace(parts[0])] = strings.TrimSpace(parts[1])
			}
		}
	}

	return mappings
}

// missingInterfaces reports which of want has no `interface=` line in the given
// dnsmasq.conf text. An interface hz was told to serve but never wrote into the
// config is a resolver that silently does not listen where the admin expects.
func missingInterfaces(configBody string, want []string) []string {
	// Collect interface= lines from the config file
	onDisk := make(map[string]bool)
	for _, line := range strings.Split(configBody, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "interface=") {
			onDisk[strings.TrimPrefix(line, "interface=")] = true
		}
	}

	var missing []string
	for _, iface := range want {
		if !onDisk[iface] {
			missing = append(missing, iface)
		}
	}
	return missing
}
