-- Config manager: registration, blessing, and machine-scoped secrets.
--
-- See plan/config-manager.md for the full model. The short version: hz has
-- never persisted anything belonging to a SERVICE — `findServiceByToken`
-- indexes into config.json, and config.json is fleet-wide state synced to HA
-- peers. A per-environment, per-app, per-role config with a version range and
-- an approval workflow does not fit there, so it gets real tables, with no
-- precedent in this schema except peer_owners.
--
-- Everything below stays inside hz's stated boundary: hz stores blobs, ranges
-- and approval state, and knows nothing about what a value MEANS. It can read
-- "invariant" and "env" values because promotion has to diff them; it is
-- structurally unable to read "secret" values, because the ciphertext is
-- sealed to a key hz is never handed (see cm_config_values below).

-- A box that wants config. One row per machine identity, independent of how
-- many (app, role) tuples it later registers — "the machine enrolls once;
-- processes fetch per role."
--
-- Approval here is a CRYPTOGRAPHIC CAPABILITY GRANT, not an authorization
-- flag: the approver pastes the environment key into the browser, wraps it TO
-- the machine's own public key, and only the wrapped blob is ever sent to hz.
-- hz relays and stores wrapped_env_key; it cannot open it, at rest or in
-- flight. An unapproved machine holds no key and can decrypt nothing even if
-- it captured every row in this database — a bug in an authorization check
-- cannot bypass that, because there is no gate to bypass, only a key that was
-- never handed over.
--
-- public_key is generated by the agent at registration and is NOT the
-- WireGuard key: reusing key material across protocols is a cheap way to be
-- wrong later, and this key's job (receiving wrapped secrets) is unrelated to
-- WireGuard's.
CREATE TABLE cm_machines (
    id                  TEXT PRIMARY KEY,
    name                TEXT NOT NULL,
    environment         TEXT NOT NULL,
    public_key          BLOB NOT NULL,
    state               TEXT NOT NULL DEFAULT 'pending' CHECK (state IN ('pending', 'approved', 'denied')),
    -- The environment key, wrapped to this machine's public_key by the
    -- approver's browser. Opaque to hz; see the table comment.
    wrapped_env_key     BLOB,
    -- Which environment key was used to wrap it, so rotation can be gradual
    -- (re-wrap and bump this, rather than an atomic fleet-wide swap).
    wrap_key_id         TEXT,
    approved_by         TEXT REFERENCES users (id) ON DELETE SET NULL,
    approved_at         TIMESTAMP,
    denied_reason       TEXT,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at        TIMESTAMP,
    -- An approved machine carries the grant that makes it approved; a denied
    -- one carries why. Enforced here, not only in Go, because the whole point
    -- of this feature is that a wrong row is refused rather than trusted.
    CHECK (state != 'approved' OR (wrapped_env_key IS NOT NULL AND wrap_key_id IS NOT NULL
        AND approved_by IS NOT NULL AND approved_at IS NOT NULL)),
    CHECK (state != 'denied' OR denied_reason IS NOT NULL),
    CHECK (state != 'pending' OR (wrapped_env_key IS NULL AND wrap_key_id IS NULL
        AND approved_by IS NULL AND approved_at IS NULL))
);

CREATE UNIQUE INDEX idx_cm_machines_name ON cm_machines (name);
CREATE INDEX idx_cm_machines_state ON cm_machines (state);
CREATE INDEX idx_cm_machines_approved_by ON cm_machines (approved_by);

-- What a machine actually runs: one row per (machine, app, role) it has ever
-- booted as. "A box runs `current`, `next` and `ops` — one machine identity,
-- several role fetches, one thing to revoke."
--
-- The FIRST registration of a tuple is the thing an admin reviews; hz has no
-- separate approval state here because that decision rides entirely on the
-- owning machine's state in cm_machines — admission control is per machine,
-- not per tuple, so a role change does not need its own workflow, only a new
-- row an admin can see. Later boots of an already-known tuple just prove
-- liveness (last_seen_at); they must never re-litigate approval, or a 3am
-- OOM-restart on prod would block on a human.
CREATE TABLE cm_registrations (
    id                  TEXT PRIMARY KEY,
    machine_id          TEXT NOT NULL REFERENCES cm_machines (id) ON DELETE CASCADE,
    app                 TEXT NOT NULL,
    role                TEXT NOT NULL,
    version             TEXT NOT NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_seen_at        TIMESTAMP,
    UNIQUE (machine_id, app, role)
);

-- No separate index on machine_id: it is the leading column of the UNIQUE
-- constraint above, which SQLite already indexes.

-- A blessed config for one (environment, app, role) address, valid over a
-- version range. This table holds only the ADDRESS and the RANGE; the values
-- live in cm_config_values so a config's shape (how many keys, what kind) is
-- never entangled with the question "does this range cover v1.2.3".
--
-- seq is the ENTIRE resolution rule. It is SQLite's own rowid, assigned once
-- by AUTOINCREMENT at insert and never touched again — not "most recently
-- modified", which is exactly the bug plan/config-manager.md names: if
-- re-blessing an old config could touch its ordering, promoting a rollback
-- fix would silently take over from a newer config nobody re-touched.
-- AUTOINCREMENT gives that guarantee for free and atomically, including
-- under concurrent inserts, which a MAX(seq)+1 read-then-write in Go cannot
-- promise against a second writer. `id` stays the ashid used everywhere else
-- as the public identifier; `seq` is purely an ordering key and is never
-- exposed as anything else.
--
-- Ranges are immutable after insert — there is deliberately no UPDATE path in
-- Go for min_ver/max_ver/seq. Superseding is a new row with an open max_ver;
-- see plan/config-manager.md "Resolution rules".
CREATE TABLE cm_configs (
    seq                 INTEGER PRIMARY KEY AUTOINCREMENT,
    id                  TEXT NOT NULL UNIQUE,
    environment         TEXT NOT NULL,
    app                 TEXT NOT NULL,
    role                TEXT NOT NULL,
    min_ver             TEXT NOT NULL,
    -- NULL means open-ended. The newest config for an address always has one;
    -- ranges only do work on rollback.
    max_ver             TEXT,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          TEXT NOT NULL REFERENCES users (id)
);

CREATE INDEX idx_cm_configs_address ON cm_configs (environment, app, role, seq);
CREATE INDEX idx_cm_configs_created_by ON cm_configs (created_by);

-- The per-key contents of a config, and where hz's read boundary actually
-- lives.
--
-- binding decides which of (value, ciphertext+key_id) is populated, and the
-- CHECK constraint below is the enforcement — not a Go-side convention, so a
-- programming mistake cannot write a "secret" that hz can quietly read, or a
-- plaintext row masquerading as sealed. 'invariant' and 'env' are both
-- plaintext to hz (promotion has to diff them); 'secret' is envelope-sealed
-- to an environment key hz never holds (see cm_machines). key_id records
-- which environment key sealed it, the same rotation seam as wrap_key_id.
CREATE TABLE cm_config_values (
    config_id           TEXT NOT NULL REFERENCES cm_configs (id) ON DELETE CASCADE,
    key                  TEXT NOT NULL,
    binding              TEXT NOT NULL CHECK (binding IN ('invariant', 'env', 'secret')),
    value                TEXT,
    ciphertext           BLOB,
    key_id               TEXT,
    PRIMARY KEY (config_id, key),
    CHECK (
        (binding = 'secret' AND value IS NULL AND ciphertext IS NOT NULL AND key_id IS NOT NULL)
        OR
        (binding != 'secret' AND value IS NOT NULL AND ciphertext IS NULL AND key_id IS NULL)
    )
);

-- No separate index on config_id: it is the leading column of the primary key
-- above, which SQLite already indexes.

-- A secret scoped to one MACHINE rather than one environment — the one
-- narrowing the model makes, because per-device revocation is a real
-- requirement an environment-wide key cannot express. Sealed directly to the
-- owning machine's public_key (cm_machines), so the environment key is never
-- in the path: setting one needs only a public key hz already publishes, not
-- the operator-held environment secret.
--
-- Durable and re-fetched on every boot, unlike the one-shot pickup the
-- iceboxed per-peer-secrets entry proposed: that entry accepted plaintext at
-- rest and deleted on read to bound exposure. Ciphertext removes what
-- delete-on-read was compensating for.
CREATE TABLE cm_machine_secrets (
    id                  TEXT PRIMARY KEY,
    machine_id          TEXT NOT NULL REFERENCES cm_machines (id) ON DELETE CASCADE,
    key                 TEXT NOT NULL,
    ciphertext          BLOB NOT NULL,
    created_at          TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          TEXT NOT NULL REFERENCES users (id),
    UNIQUE (machine_id, key)
);

-- No separate index on machine_id: it is the leading column of the UNIQUE
-- constraint above, which SQLite already indexes.
CREATE INDEX idx_cm_machine_secrets_created_by ON cm_machine_secrets (created_by);

-- Audit trail for every secret plaintext handed out — the read side of "reads
-- audited" in plan/config-manager.md's per-key metadata table. hz never sees
-- secret plaintext itself (it only ever relays ciphertext), so a row here
-- records that a RELAY happened: who asked, for which machine or config
-- address, which key, and from where. It is not a decrypt log, because hz
-- cannot produce one.
--
-- machine_id and config_id are nullable and ON DELETE SET NULL rather than
-- CASCADE: this table is evidence, and evidence must outlive the thing it is
-- evidence about, the same reasoning PurgeExpiredSessions uses to keep
-- recently-revoked sessions around.
CREATE TABLE cm_secret_reads (
    id                  TEXT PRIMARY KEY,
    at                  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actor               TEXT NOT NULL,
    machine_id          TEXT REFERENCES cm_machines (id) ON DELETE SET NULL,
    config_id           TEXT REFERENCES cm_configs (id) ON DELETE SET NULL,
    secret_key          TEXT NOT NULL,
    source_ip           TEXT
);

CREATE INDEX idx_cm_secret_reads_machine ON cm_secret_reads (machine_id);
CREATE INDEX idx_cm_secret_reads_config ON cm_secret_reads (config_id);
CREATE INDEX idx_cm_secret_reads_at ON cm_secret_reads (at);
