package integration

import (
	"encoding/json"
	"fmt"
	"strings"
)

// ScrapeYAML renders a Prometheus scrape_configs document for the given targets:
// one job per service, one static_config per slot (so the slot label is correct),
// with metrics_path and optional bearer auth taken per service. The output is a
// complete, drop-in scrape config the operator can include or serve to Prometheus.
//
// Targets are expected pre-sorted (Detector.Healthy does this) so the output is
// stable across refreshes.
func ScrapeYAML(targets []Target) string {
	var sb strings.Builder
	sb.WriteString("# Generated by homelab-horizon — do not edit.\n")
	sb.WriteString("# Source: GET /integration/prometheus/scrape.yaml\n")
	sb.WriteString("scrape_configs:\n")

	for _, g := range groupByService(targets) {
		head := g.targets[0]
		sb.WriteString(fmt.Sprintf("  - job_name: %s\n", yamlScalar(g.service)))
		sb.WriteString(fmt.Sprintf("    metrics_path: %s\n", yamlScalar(head.MetricsPath)))
		if head.Bearer != "" {
			sb.WriteString("    authorization:\n")
			sb.WriteString("      type: Bearer\n")
			sb.WriteString(fmt.Sprintf("      credentials: %s\n", yamlScalar(head.Bearer)))
		}
		sb.WriteString("    static_configs:\n")
		for _, t := range g.targets {
			sb.WriteString(fmt.Sprintf("      - targets: [%s]\n", yamlScalar(t.Address)))
			sb.WriteString("        labels:\n")
			sb.WriteString(fmt.Sprintf("          service: %s\n", yamlScalar(t.Service)))
			if t.Slot != "" {
				sb.WriteString(fmt.Sprintf("          slot: %s\n", yamlScalar(t.Slot)))
			}
		}
	}
	return sb.String()
}

// httpSDEntry is one Prometheus http_sd_config record.
type httpSDEntry struct {
	Targets []string          `json:"targets"`
	Labels  map[string]string `json:"labels"`
}

// HTTPSDTargets renders the Prometheus http_sd_config JSON for the targets. The
// operator points a single Prometheus job at this endpoint; targets, slot labels,
// and per-target metrics_path are discovered dynamically (no Prometheus reload on
// service/slot changes).
//
// Limitation: http_sd has no per-target auth, so a service that needs a bearer
// token (MetricsIntegration.Bearer) must be scraped via scrape.yaml instead; such
// targets are still listed here (reachable when the job-level auth matches) but
// the token is not carried. Network-restricted services (the default) are fine.
func HTTPSDTargets(targets []Target) ([]byte, error) {
	entries := make([]httpSDEntry, 0, len(targets))
	for _, t := range targets {
		labels := map[string]string{
			"service":          t.Service,
			"__metrics_path__": t.MetricsPath,
			"__scheme__":       "http",
		}
		if t.Slot != "" {
			labels["slot"] = t.Slot
		}
		entries = append(entries, httpSDEntry{Targets: []string{t.Address}, Labels: labels})
	}
	return json.MarshalIndent(entries, "", "  ")
}

type serviceGroup struct {
	service string
	targets []Target
}

// groupByService groups pre-sorted targets into per-service runs, preserving
// first-seen service order.
func groupByService(targets []Target) []serviceGroup {
	var groups []serviceGroup
	idx := map[string]int{}
	for _, t := range targets {
		i, ok := idx[t.Service]
		if !ok {
			idx[t.Service] = len(groups)
			groups = append(groups, serviceGroup{service: t.Service, targets: []Target{t}})
			continue
		}
		groups[i].targets = append(groups[i].targets, t)
	}
	return groups
}

// yamlScalar quotes a scalar when needed so generated YAML is always valid.
func yamlScalar(s string) string {
	if s == "" {
		return `""`
	}
	if strings.ContainsAny(s, ` :#{}[],&*!|>'"%@`+"`\n\t") {
		return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(s) + `"`
	}
	return s
}
