package integration

import (
	"encoding/json"
	"fmt"
	"sort"
	"strings"
)

// ScrapeJob is one renderable Prometheus job: a job_name, a job-level metrics
// path and optional bearer, and its targets. It is the neutral representation
// both service metrics and non-service exporters are rendered from, so the
// renderers stay agnostic about where a target came from.
type ScrapeJob struct {
	Name        string
	MetricsPath string // job-level; defaults to /metrics if empty
	Bearer      string
	Targets     []ScrapeTarget
}

// ScrapeTarget is one endpoint within a job, with its per-target static labels.
type ScrapeTarget struct {
	Address string
	Labels  map[string]string
}

func (j ScrapeJob) metricsPath() string {
	if j.MetricsPath == "" {
		return "/metrics"
	}
	return j.MetricsPath
}

// ServiceJobs converts probed-healthy service targets into ScrapeJobs: one job
// per service, one target per slot, labeled by service (and slot when the
// blue-green model is in use). Targets are expected pre-sorted (Detector.Healthy
// does this) so job/target order is stable across refreshes.
func ServiceJobs(targets []Target) []ScrapeJob {
	var jobs []ScrapeJob
	idx := map[string]int{}
	for _, t := range targets {
		i, ok := idx[t.Service]
		if !ok {
			i = len(jobs)
			idx[t.Service] = i
			jobs = append(jobs, ScrapeJob{Name: t.Service, MetricsPath: t.MetricsPath, Bearer: t.Bearer})
		}
		labels := map[string]string{"service": t.Service}
		if t.Slot != "" {
			labels["slot"] = t.Slot
		}
		jobs[i].Targets = append(jobs[i].Targets, ScrapeTarget{Address: t.Address, Labels: labels})
	}
	return jobs
}

// ScrapeYAML renders a complete Prometheus scrape_configs document for the given
// jobs — one job_name per job, one static_config per target so per-target labels
// are correct, with metrics_path and optional bearer per job. The output is a
// drop-in scrape config an operator includes via scrape_config_files or serves
// to Prometheus. Jobs are expected pre-ordered so the output is stable.
func ScrapeYAML(jobs []ScrapeJob) string {
	var sb strings.Builder
	sb.WriteString("# Generated by homelab-horizon — do not edit.\n")
	sb.WriteString("# Source: GET /integration/prometheus/scrape.yaml\n")
	sb.WriteString("scrape_configs:\n")

	for _, j := range jobs {
		fmt.Fprintf(&sb, "  - job_name: %s\n", yamlScalar(j.Name))
		fmt.Fprintf(&sb, "    metrics_path: %s\n", yamlScalar(j.metricsPath()))
		if j.Bearer != "" {
			sb.WriteString("    authorization:\n")
			sb.WriteString("      type: Bearer\n")
			fmt.Fprintf(&sb, "      credentials: %s\n", yamlScalar(j.Bearer))
		}
		sb.WriteString("    static_configs:\n")
		for _, t := range j.Targets {
			fmt.Fprintf(&sb, "      - targets: [%s]\n", yamlScalar(t.Address))
			if len(t.Labels) > 0 {
				sb.WriteString("        labels:\n")
				for _, k := range sortedKeys(t.Labels) {
					fmt.Fprintf(&sb, "          %s: %s\n", k, yamlScalar(t.Labels[k]))
				}
			}
		}
	}
	return sb.String()
}

// httpSDEntry is one Prometheus http_sd_config record.
type httpSDEntry struct {
	Targets []string          `json:"targets"`
	Labels  map[string]string `json:"labels"`
}

// HTTPSDTargets renders the Prometheus http_sd_config JSON for the jobs. A single
// Prometheus job points at this endpoint; targets, labels, per-target
// metrics_path, and job identity are discovered dynamically (no Prometheus
// reload on service/exporter changes). The job_name is carried as the reserved
// `job` label so multiple hz jobs coexist under one Prometheus http_sd config.
//
// Limitation: http_sd has no per-target auth, so a target that needs a bearer
// token must be scraped via scrape.yaml instead; such targets are still listed
// here (reachable when the job-level auth matches) but the token is not carried.
func HTTPSDTargets(jobs []ScrapeJob) ([]byte, error) {
	entries := make([]httpSDEntry, 0)
	for _, j := range jobs {
		path := j.metricsPath()
		for _, t := range j.Targets {
			labels := map[string]string{
				"job":              j.Name,
				"__metrics_path__": path,
				"__scheme__":       "http",
			}
			for k, v := range t.Labels {
				labels[k] = v
			}
			entries = append(entries, httpSDEntry{Targets: []string{t.Address}, Labels: labels})
		}
	}
	return json.MarshalIndent(entries, "", "  ")
}

func sortedKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// yamlScalar quotes a scalar when needed so generated YAML is always valid.
func yamlScalar(s string) string {
	if s == "" {
		return `""`
	}
	if strings.ContainsAny(s, ` :#{}[],&*!|>'"%@`+"`\n\t") {
		return `"` + strings.NewReplacer(`\`, `\\`, `"`, `\"`).Replace(s) + `"`
	}
	return s
}
